// ============================================================
// CEREBRO — PipBoyData.gs
// Pip-Boy: dane statyczne (suplementy, szablony dnia, kalibracja HP,
// biblioteka cytatow i komunikatow marquee)
// Zrodlo specyfikacji: docs/Pip-Boy-Koncept.md
// ============================================================

// ---- Moduł 1: Suplementacja (sekcja 2.0 + Moduł 1) ----
const PIPBOY_SUPLEMENTY_RDZENNE = [
  { klucz: 'kreatyna', nazwa: 'Kreatyna', pora: 'rano' },
  { klucz: 'vita_pak', nazwa: 'KFD Vita Pak', pora: 'rano' },
  { klucz: 'kolagen', nazwa: 'KFD Kolagen Plus', pora: 'rano' },
  { klucz: 'omega3', nazwa: 'KFD Ultra Omega 3 Plus', pora: 'rano' },
];
// Melatonina: WARUNKOWA (Runda #17 — cofniecie zmiany z Rundy #14). Trackowana
// tylko gdy zazyta, bez kary HP i bez pola "nie byla potrzebna" (decyzja Arka).
const PIPBOY_MELATONINA = { klucz: 'melatonina', nazwa: 'Melatonina', limit_max: 5 };
// Gainer: OBLIGATORYJNY w dni treningowe, osobny punkt zywieniowy (Modul 1 + Modul 4)
const PIPBOY_GAINER = { klucz: 'gainer', nazwa: 'KFD X Gainer' };

// ---- Moduł 4: Dieta — orientacyjne pory 5 posiłków wg Szablonu Dnia (sekcja 3) ----
// Godziny sa punktem odniesienia dla reminderow, nie sztywnymi blokami.
const PIPBOY_POSILKI_SZABLONY = {
  A: ['7:30', '10:30', '13:30', '16:15', '19:00'],
  B: ['8:30', '11:00', '14:00', '17:00', '20:30'],
  C: ['8:15', '11:00', '13:00', '16:00', '19:00'],
  D: ['8:30', '11:00', '13:00', '16:00', '19:00'],
};

// ---- Sekcja 4.2: kalibracja HP (FINALNA, Runda #9/#14, zaktualizowana #17) ----
const PIPBOY_HP_KARY = {
  suplement_rdzenny_lub_gainer: 3,   // za kazda pozycje z 5 (Kreatyna/VitaPak/Kolagen/Omega3/Gainer w dt)
  melatonina: 0,                     // Runda #17 — warunkowa, bez kary
  posilek: 6,                        // za kazdy z 5
  trening_w_dniu_treningowym: 30,    // pelny blok 1h15
  czytelnictwo_zero_dnia: 8,
  mood_wpis: 5,                      // za kazdy z 2 (rano/wieczor)
  sprzatanie_ponizej_floora: 5,      // nie dotyczy niedzieli
  pielegnacja: 0,                    // Runda #14 — bez kary
};

// ---- Sekcja 4.1: krzywa XP — XP(poziom) = 3*poziom^2 + 47*poziom ----
function pipboyXpDoNastepnegoPoziomu(poziom) {
  const next = 3 * Math.pow(poziom + 1, 2) + 47 * (poziom + 1);
  const curr = 3 * Math.pow(poziom, 2) + 47 * poziom;
  return next - curr;
}

// ---- Sekcja 4.1a: GOD_MODE_24H — limit i zakres ochrony ----
const PIPBOY_GOD_MODE_LIMIT_MIESIECZNY = 4;
const PIPBOY_GOD_MODE_WYLACZENIA = ['suplementy_rdzenne']; // te zawsze obowiazkowe

// 263 cytatow, zrodlo: docs/data/cytaty-motywacyjne.csv (Runda #19)
const PIPBOY_QUOTES = [
  { tresc: 'Dla każdego, kto się boi, jest samotny albo nieszczęśliwy, stanowczo najlepszym środkiem jest wyjście na zewnątrz, gdzieś, gdzie jest się zupełnie sam na sam z niebem, naturą i Bogiem. Bo dopiero wtedy, tylko wtedy, czuje się, że wszystko jest tak, jak być powinno i że Bóg chce widzieć ludzi szczęśliwymi wśród prostej, ale pięknej natury. Jak długo to istnieje, a będzie na pewno zawsze istnieć, wiem, że we wszystkich okolicznościach, istnieje zawsze pociecha na każde zmartwienie. I wierzę mocno, że natura potrafi ukoić każde cierpienie.', autor: 'Anna Frank', zrodlo: 'tekstualna.pl' },
  { tresc: 'Lepiej jest zapalić świecę, niż przeklinać ciemność.', autor: 'Matka Teresa z Kalkuty', zrodlo: 'tekstualna.pl' },
  { tresc: 'Mistrzowie grają dotąd, aż grają dobrze.', autor: 'Billie Jean King', zrodlo: 'tekstualna.pl' },
  { tresc: 'Czyń tylko to co podpowiada Ci serce.', autor: 'Diana Spencer', zrodlo: 'tekstualna.pl' },
  { tresc: 'Jeśli zaproponują ci miejsce w statku kosmicznym, nie pytaj, co to za miejsce. Po prostu wsiadaj.', autor: 'Sheryl Sandberg', zrodlo: 'tekstualna.pl' },
  { tresc: 'Rób to, co uważasz za stosowne. I tak zawsze znajdzie się ktoś, kto uważa inaczej…', autor: 'Michelle Obama', zrodlo: 'tekstualna.pl' },
  { tresc: 'Najtrudniejsze jest zdecydowanie się na działanie. Reszta to już tylko kwestia wytrwałości.', autor: 'Amelia Earhart', zrodlo: 'tekstualna.pl' },
  { tresc: 'Być może urodziłaś się bez skrzydeł. Ale najważniejsze, żebyś nie przeszkadzała im wyrosnąć.', autor: 'Coco Chanel', zrodlo: 'tekstualna.pl' },
  { tresc: 'Zawsze robiłam coś do czego nie byłam w pełni przygotowana. Myślę, że właśnie tak rośniesz.', autor: 'Marissa Mayer', zrodlo: 'tekstualna.pl' },
  { tresc: 'Przyszedł ten dzień, kiedy ryzyko trwania w pąku było bardziej bolesne niż ryzyko zakwitnięcia.', autor: 'Anais Nin', zrodlo: 'tekstualna.pl' },
  { tresc: 'Kiedyś – nie ma takiego dnia tygodnia.', autor: 'Janet Dailey', zrodlo: 'tekstualna.pl' },
  { tresc: 'Wznoś się po każdym upadku, padniesz trupem albo urosną Ci skrzydła.', autor: 'Maria von Ebner-Eschenbach', zrodlo: 'tekstualna.pl' },
  { tresc: 'W życiu nie zawsze wygrywają najmądrzejsi, najpiękniejsi i najbardziej przebojowi. Wygrywają ci, którzy postanawiają wygrać.', autor: 'Kamila Rowińska', zrodlo: 'tekstualna.pl' },
  { tresc: 'Dawać bez wahania, tracić bez żalu i zdobywać bez chciwości…', autor: 'George Sand', zrodlo: 'tekstualna.pl' },
  { tresc: 'Nigdy nie marnuj czasu, próbując wytłumaczyć kim jesteś ludziom, którzy postanowili Cię nie zrozumieć.', autor: 'Dream Hampton', zrodlo: 'tekstualna.pl' },
  { tresc: 'Dawanie otwiera drogę do otrzymywania.', autor: 'Florence Scovel Shinn', zrodlo: 'tekstualna.pl' },
  { tresc: 'Nauczyłam się, że droga postępu nie jest ani szybka, ani łatwa.', autor: 'Maria Skłodowska-Curie', zrodlo: 'tekstualna.pl' },
  { tresc: 'W życiu nie chodzi o czekanie aż burza minie. Chodzi o to, by nauczyć się tańczyć w deszczu.', autor: 'Vivian Green', zrodlo: 'tekstualna.pl' },
  { tresc: 'Jeśli chcesz dobrze dla swoich dzieci, to spędzaj z nimi dwa razy więcej czasu i wydawaj na nie dwa razy mniej pieniędzy.', autor: 'Abigail Van Buren', zrodlo: 'tekstualna.pl' },
  { tresc: 'Zbyt często ludzie pracują ciężko nad niewłaściwą rzeczą. Pracować nad właściwą rzeczą jest prawdopodobnie ważniejsze niż pracować ciężko.', autor: 'Caterina Fake', zrodlo: 'tekstualna.pl' },
  { tresc: 'Jeśli idziesz za swoim marzeniem, to będziesz testowany.', autor: 'Kim Kiyosaki', zrodlo: 'tekstualna.pl' },
  { tresc: 'Ego mówi: gdy wszystko się ułoży, wówczas poczuję spokój. Duch mówi: znajdź swój spokój i wszystko się ułoży.', autor: 'Marianne Williamson', zrodlo: 'tekstualna.pl' },
  { tresc: 'Kiedy ktoś przechodzi właśnie przez burzę, twoja cicha obecność jest potężniejsza niż milion pustych słów', autor: 'Thema Davis', zrodlo: 'tekstualna.pl' },
  { tresc: 'Albo wygram albo zdechnę.', autor: 'Justyna Kowalczyk', zrodlo: 'tekstualna.pl' },
  { tresc: 'Twoje poczucie własnej wartości zależy tylko od ciebie. Nie musisz pozwalać nikomu mówić ci, kim masz być.', autor: 'Beyonce', zrodlo: 'tekstualna.pl' },
  { tresc: 'Nasz rozwój nigdy się nie kończy, składa się z mnóstwa etapów i kiedy już człowiek myśli, że osiągnął ostatni, otwiera się przed nim kolejny. Ale właśnie to jest fantastyczne! To jak obieranie karczocha, dokopywanie się do tej miękkiej i słodkiej części. Zrzucanie kolejnych twardych, ograniczających warstw.', autor: 'Agnieszka Maciąg', zrodlo: 'tekstualna.pl' },
  { tresc: 'Można mieć wszystko. Po prostu nie można mieć wszystkiego jednocześnie.', autor: 'Oprah Winfrey', zrodlo: 'tekstualna.pl' },
  { tresc: 'Pamiętam, że miałam bardzo mało pieniędzy, że głodowałam i kontrolowałam wydatki. Że musiałam podejmować decyzje, czy dzisiaj kupić paczkę orzeszków ziemnych i kubełek jogurtu, czy jutro kupić dużą torbę serowego popcornu i karton soku żurawinowego. Tym się wtedy żywiłam. Ale nie brałam pod uwagi innej możliwości niż sukces.', autor: 'Madonna', zrodlo: 'tekstualna.pl' },
  { tresc: 'Jeżeli jesteś nastawiony na to żeby wszyscy cię lubili, będziesz gotowy poświęcić wszystko każdego dnia i niczego nie osiągniesz.', autor: 'Margaret Thatcher', zrodlo: 'tekstualna.pl' },
  { tresc: 'Zagłuszanie bólu na jakiś czas sprawia, że powraca ze zdwojoną siłą.', autor: 'J.K Rowling', zrodlo: 'tekstualna.pl' },
  { tresc: 'Pamiętaj, że kiedy potrzebujesz pomocnej dłoni – jest ona na końcu twojego ramienia. Gdy jesteś starszy, pamiętaj, że masz drugą dłoń: pierwsza jest po to aby pomagać sobie, druga, żeby pomagać innym.', autor: 'Audrey Hepburn', zrodlo: 'tekstualna.pl' },
  { tresc: 'Kobieta jest jak torebka z herbatą. Nie wiadomo, jak jest mocna, dopóki nie znajdzie się w gorącej wodzie', autor: 'Eleonor Roosevelt', zrodlo: 'tekstualna.pl' },
  { tresc: 'Mieć trudne życie – to wielki przywilej.', autor: 'Indira Gandhi', zrodlo: 'tekstualna.pl' },
  { tresc: 'Lepiej być nieszczęśliwą samotnie, niż nieszczęśliwą z kimś innym.', autor: 'Marilyn Monroe', zrodlo: 'tekstualna.pl' },
  { tresc: 'Podnoszę mój głos – nie po to, by krzyczeć, ale po to, by ci bez głosu mogli zostać usłyszani', autor: 'Malala Yousafzai', zrodlo: 'tekstualna.pl' },
  { tresc: 'To może zabrzmieć jak banał, ale kiedy czujesz się piękna i silna w środku, to widać na zewnątrz.', autor: 'Angelina Jolie', zrodlo: 'tekstualna.pl' },
  { tresc: 'Jak sam sobie prasujesz, to woda sodowa do głowy ci nie uderzy.', autor: 'Meryl Streep', zrodlo: 'tekstualna.pl' },
  { tresc: 'To twoje miejsce na świecie i twoje życie; idź i zrób z nim to, co tylko możesz, uczyń z niego to życie, które chciałbyś przeżyć.', autor: 'Mae Jemison', zrodlo: 'tekstualna.pl' },
  { tresc: 'Nigdy nie jest za późno – za późno by zmienić swoje życie, za późno by być szczęśliwym.', autor: 'Jane Fonda', zrodlo: 'tekstualna.pl' },
  { tresc: 'Żyje się tylko raz, ale jeśli żyjesz dobrze, ten raz wystarczy.', autor: 'Mae West', zrodlo: 'tekstualna.pl' },
  { tresc: 'W życiu nie ma rzeczy, których można żałować; są tylko rzeczy, na których można się uczyć.', autor: 'Jennifer Aniston', zrodlo: 'tekstualna.pl' },
  { tresc: 'Myślę, że wypalenie jest kwestią złości. Można je przezwyciężyć, znajdując to, co cię złości i przezwyciężając to.', autor: 'Marissa Mayer', zrodlo: 'tekstualna.pl' },
  { tresc: 'Jeśli masz marzenie, musisz uchwycić się go i nigdy nie puszczać.', autor: 'Carol Burnett', zrodlo: 'tekstualna.pl' },
  { tresc: 'Życie jest niesamowicie ciekawe i zaskakujące.. po jakimś czasie twoje największe cierpienia zamieniają się w źródła twojej największej siły.', autor: 'Drew Barrymore', zrodlo: 'tekstualna.pl' },
  { tresc: 'Jeśli ktoś uśmiecha się do ciebie, odpowiedz mu tym samym.', autor: 'Dolly Parton', zrodlo: 'tekstualna.pl' },
  { tresc: 'Dowiedz się, kim jesteś i trzymaj się tego. To po to zostałeś umieszczony w tym życiu. Odnajdź tę jedną prawdę, a wszystko inne przyjdzie wraz z nią.', autor: 'Ellen Degeneres', zrodlo: 'tekstualna.pl' },
  { tresc: 'Nie boję się sztormów i burz, dzięki nim uczę się, jak żeglować moim statkiem.', autor: 'Louisa May Alcott', zrodlo: 'tekstualna.pl' },
  { tresc: 'Marzenie jest formą planowania.', autor: 'Gloria Steinem', zrodlo: 'tekstualna.pl' },
  { tresc: 'Ludzie najczęściej rezygnują ze swej siły poprzez myślenie, że nie mają żadnej.', autor: 'Alice Walker', zrodlo: 'tekstualna.pl' },
  { tresc: 'Jeśli widzisz, że musisz upaść, upadnij przynajmniej w wielkim stylu.', autor: 'Cate Blanchett', zrodlo: 'tekstualna.pl' },
  { tresc: 'Nie pozwól nigdy nikomu mówić ci, że nie masz prawa być tym, kim jesteś.', autor: 'Lady Gaga', zrodlo: 'tekstualna.pl' },
  { tresc: 'Determinacja to poniesienie porażki 19 razy i odniesienie sukcesu za 20. razem.', autor: 'Julie Andrews', zrodlo: 'tekstualna.pl' },
  { tresc: 'Bez otwartego umysłu nie da się odnieść sukcesu.', autor: 'Martha Stewart', zrodlo: 'tekstualna.pl' },
  { tresc: 'Nie ograniczaj siebie. Jesteś wszystkim, co masz.', autor: 'Janis Joplin', zrodlo: 'tekstualna.pl' },
  { tresc: 'Nie można żyć, naśladując kogoś innego. Oznacza to życie pozbawione wszelkich prawdziwych emocji.', autor: 'Billie Holiday', zrodlo: 'tekstualna.pl' },
  { tresc: 'Niezależnie od tego, skąd jesteś, twoje marzenia są ważne.', autor: 'Lupita Nyong\'o', zrodlo: 'tekstualna.pl' },
  { tresc: 'Nie można nikogo nakłonić do zmiany. Każdy z nas pilnuje własnej furtki do zmian, która otwiera się tylko od wewnątrz. Nie możemy otworzyć furtki innym, odwołując się czy to do argumentów, czy do uczuć.', autor: 'Marilyn Ferguson', zrodlo: 'tekstualna.pl' },
  { tresc: 'Wdzięczność otwiera pełnię życia. Sprawia, że to, co mamy, wystarcza. Zamienia opór w akceptację, chaos w porządek, konfuzję w klarowność. Może zamienić posiłek w ucztę, mieszkanie w dom, obcego w przyjaciela. Wdzięczność nadaje sens przeszłości, przynosi pokój dzisiaj i tworzy wizję jutra.', autor: 'Melody Beattie', zrodlo: 'tekstualna.pl' },
  { tresc: 'Ciężki jest los współczesnej kobiety. Musi ubierać się jak chłopak, wyglądać jak dziewczyna, myśleć jak mężczyzna i pracować jak koń.', autor: 'Elizabeth Taylor', zrodlo: 'tekstualna.pl' },
  { tresc: 'Jakże często szczęście bywa zaprzepaszczone przez zbyt długie przygotowania – głupie przygotowania!', autor: 'Jane Austen', zrodlo: 'tekstualna.pl' },
  { tresc: 'Jak można stać się motylem? Musisz tak bardzo chcieć latać, że jesteś gotów porzucić bycie gąsienicą.', autor: 'Trina Paulus', zrodlo: 'tekstualna.pl' },
  { tresc: 'Prawdziwą miarą osoby jest to jak traktuje tych, którzy nie mogą wyświadczyć jej żadnej przysługi.', autor: 'Ann Landers', zrodlo: 'tekstualna.pl' },
  { tresc: 'Teraz już chyba należą mi się od życia same przyjemności.', autor: 'Danuta Wałęsa', zrodlo: 'tekstualna.pl' },
  { tresc: 'Fajnie jest, dobrze jest, nie rycz.', autor: 'Magda Danaj', zrodlo: 'tekstualna.pl' },
  { tresc: 'Prawda jest taka, że ludzie, których spotykasz na swej drodze, będą traktować cię identycznie, jak ty traktujesz samą siebie.', autor: 'Miranda Kerr', zrodlo: 'tekstualna.pl' },
  { tresc: 'Zawsze bądź pierwszorzędną wersją siebie zamiast drugorzędną wersją kogoś innego.', autor: 'Judy Garland', zrodlo: 'tekstualna.pl' },
  { tresc: 'Kobieta luksusowa to taka, która ma własne konto. Jest niezależna finansowo.', autor: 'Dorota Wellman', zrodlo: 'tekstualna.pl' },
  { tresc: 'Próbuję sobie przypomnieć rzecz, której żałuję. Nie ma takiej.', autor: 'Agata Kulesza', zrodlo: 'tekstualna.pl' },
  { tresc: 'Ja się urodziłam z pomysłem na całe swoje życie.', autor: 'Eva Minge', zrodlo: 'tekstualna.pl' },
  { tresc: 'Nie wyobrażam sobie, aby można było osiągnąć sukces, nie będąc konsekwentnym i upartym.', autor: 'Irena Eris', zrodlo: 'tekstualna.pl' },
  { tresc: 'Zawsze przestrzegałam zasady, by nigdy nie spędzać nawet pięciu minut z ludźmi, którzy nie chcą być ze mną.', autor: 'Beata Tyszkiewicz', zrodlo: 'tekstualna.pl' },
  { tresc: 'Dla miłości nie jest ważne, aby ludzie do siebie pasowali, ale by byli razem szczęśliwi.', autor: 'Brigitte Bardot', zrodlo: 'tekstualna.pl' },
  { tresc: 'Móc czegoś nie chcieć, to już jest szczęście.', autor: 'Maria Dąbrowska', zrodlo: 'tekstualna.pl' },
  { tresc: 'Każdemu, kto tonie, należy podać rękę!', autor: 'Irena Sendlerowa', zrodlo: 'tekstualna.pl' },
  { tresc: 'Niemożliwe nie może się zdarzyć, wobec tego pozornie niemożliwe musi być możliwe.', autor: 'Agatha Christie', zrodlo: 'tekstualna.pl' },
  { tresc: 'Czynienie dobra powinno przede wszystkim dotyczyć nas samych. Wyzbywam się więc złych emocji, które nagromadzone we mnie sprawiają, że cierpią na tym najbliższe mi osoby. Staram się więc nie ulegać impulsom, nie złościć, być po prostu na co dzień życzliwą. To działa w obie strony, bo im ja jestem lepsza dla siebie, tym jestem lepsza dla innych.', autor: 'Ania Przybylska', zrodlo: 'tekstualna.pl' },
  { tresc: 'Każdy miewa w życiu momenty, kiedy musi się zastanowić, kim jest i czego chce.', autor: 'Julia Roberts', zrodlo: 'tekstualna.pl' },
  { tresc: 'Nigdy nie odmawiaj zaproszenia. Nigdy nie opieraj się nieznanemu. Po prostu otwórz się na świat i napawaj przeżyciami. A jeśli się sparzysz? Cóż, trudno… Pewnie nie na darmo…', autor: 'Martyna Wojciechowska', zrodlo: 'tekstualna.pl' },
  { tresc: 'Tyle wiemy o sobie, ile nas sprawdzono.', autor: 'Wisława Szymborska', zrodlo: 'tekstualna.pl' },
  { tresc: 'Nie tęskni się za tym, czego się nie doświadczyło.', autor: 'Katarzyna Grochola', zrodlo: 'tekstualna.pl' },
  { tresc: 'Moja historia nie wyglądała tak, że pracowałam w McDonald\'s, ktoś mnie zauważył i następnego dnia chodziłam po wybiegu. To była świadoma decyzja, marzenie, do którego dążyłam.', autor: 'Anja Rubik', zrodlo: 'tekstualna.pl' },
  { tresc: 'Rozśmiesza mnie wszystko. I cieszę się, że tak jest. Musisz zawsze znaleźć jakiś powód do śmiechu, bo inaczej – życie staje się bez sensu.', autor: 'Cameron Diaz', zrodlo: 'tekstualna.pl' },
  { tresc: 'To wybór, a nie przypadek, decyduje o twoim przeznaczeniu. Sam musisz zdecydować, ile jesteś wart, jaką odgrywasz rolę w świecie i w jaki sposób nadajesz mu sens. Nikt inny nie dysponuje tym, co ty-twoim zestawem talentów, pomysłów, zainteresowań. Jesteś oryginalnym egzemplarzem. Arcydziełem.', autor: 'Regina Brett', zrodlo: 'tekstualna.pl' },
  { tresc: 'Nic tak nie rozwija, jak zdrowa rywalizacja. Uważam, że tylko konkurencja skłania nas do ciągłego rozwoju.', autor: 'Joanna Przetakiewicz', zrodlo: 'tekstualna.pl' },
  { tresc: 'Dla mnie receptą jest niezmuszanie się do niczego. Ja robię to, na co mam ochotę.', autor: 'Krystyna Janda', zrodlo: 'tekstualna.pl' },
  { tresc: 'Moja praca – to ja.', autor: 'Gosia Baczyńska', zrodlo: 'tekstualna.pl' },
  { tresc: 'Jesteśmy tym, czego pragniemy.', autor: 'Erica Jong', zrodlo: 'tekstualna.pl' },
  { tresc: 'Na zawsze składa się z wielu teraz.', autor: 'Emily Dickinson', zrodlo: 'tekstualna.pl' },
  { tresc: 'Jest niewiele lepszych dróg do porozumienia od dialogu.', autor: 'Bożena Walter', zrodlo: 'tekstualna.pl' },
  { tresc: 'Jeżeli jest mi źle, to nie marudzę i zmieniam to, co mi doskwiera.', autor: 'Katarzyna Bujakiewicz', zrodlo: 'tekstualna.pl' },
  { tresc: 'Można się tak całe życie zastanawiać, czy wyjść z domu, czy może lepiej zostać, bo zacznie padać deszcz. Ja po prostu wychodzę i nie kombinuję.', autor: 'Agnieszka Dygant', zrodlo: 'tekstualna.pl' },
  { tresc: 'Uważam, że nie pracuje się tylko po to, by się utrzymać. Trzeba robić coś, co daje satysfakcję niematerialną.', autor: 'Ewa Błaszczyk', zrodlo: 'tekstualna.pl' },
  { tresc: 'Kiedy się działa, mniej boli.', autor: 'Anna Dymna', zrodlo: 'tekstualna.pl' },
  { tresc: 'Według mnie piękno to nie ładna czy wyprasowana buzia, ale wewnętrzne światło.', autor: 'Danuta Stenka', zrodlo: 'tekstualna.pl' },
  { tresc: 'Ten tramwaj dalej nie jedzie.', autor: 'Henryka Krzywonos', zrodlo: 'tekstualna.pl' },
  { tresc: 'Dla mnie największym afrodyzjakiem jest dom pachnący cynamonem i jabłkami. Tak pachnie dom szczęśliwy.', autor: 'Ewa Wachowicz', zrodlo: 'tekstualna.pl' },
  { tresc: 'Życie jest za piękne, aby żyć normalnie.', autor: 'Maria Czubaszek', zrodlo: 'tekstualna.pl' },
  { tresc: 'Staram się żyć każdym dniem, cieszyć się tym, co przynosi. Myśleć o tym, co dobre, a nie złe. Bo tak jest łatwiej. Nie przejmować się tym, co było, ani tym, co mnie jeszcze czeka. Wiadomo, że to nie jest proste. Ale nie wybiegam daleko w przyszłość, najdalej o dzień, dwa. Żyję chwilą. Dużo przeszłam i to mnie nauczyło, że nie warto wszystkiego planować. Życie i tak pisze swój własny scenariusz.', autor: 'Agata Mróz-Olszewska', zrodlo: 'tekstualna.pl' },
  { tresc: 'Szczęście się nie kończy, ono ulega zmianom.', autor: 'Lolita Pille', zrodlo: 'tekstualna.pl' },
  { tresc: 'Kiedy tak patrzę na to, co się z przyrodą dzieje w maju, na to co i kogo mam, to się zastanawiam jak do cholery mogę choć na jedną chwilę zapomnieć o niekończących się możliwościach, które daje mi moje życie?', autor: 'Basia Szmydt', zrodlo: 'tekstualna.pl' },
  { tresc: 'Nasze największe słabości leżą w rezygnacji.', autor: 'Thomas Edison', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Sukces to nie ostateczność, porażka to nie fatalność: to odwaga, by kontynuować, jest tym, co się liczy.', autor: 'Winston Churchill', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Bądź zmianą, którą chcesz zobaczyć na świecie.', autor: 'Mahatma Gandhi', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Trudne drogi często prowadzą do pięknych destynacji.', autor: 'Zig Ziglar', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Nie bój się porażki. To nie koniec, to tylko początek.', autor: 'Barack Obama', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Jedyną przeszkodą między tobą a twoim celem jest historia, którą ciągle sobie powtarzasz i która opowiada o tym… dlaczego nie możesz go osiągnąć.', autor: 'Jordan Belfort', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Nigdy nie jest za późno, aby być tym, kim chcesz być.', autor: 'George Eliot', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Porażka jest po prostu okazją do tego, by zaczęcia jeszcze raz, tym razem bardziej inteligentnie.', autor: 'Henry Ford', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Wszystko, co możemy zrobić, to to, co jest przed nami.', autor: 'J.R.R. Tolkien', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Nie ma niczego trwalszego niż tymczasowość.', autor: 'Pablo Picasso', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Porażka nie jest przeciwna sukcesowi, jest jej częścią.', autor: 'Arianna Huffington', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Nie chodzi o to, ile masz, ale ile czerpiesz z tego, co masz.', autor: 'Oprah Winfrey', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Nie mierzy się człowieka liczbą jego upadków. Liczy się to, ile razy wstanie.', autor: 'Nelson Mandela', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Jeśli masz marzenie, musisz je doścignąć.', autor: 'Will Smith', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Najważniejsze, aby nigdy nie przestawać zadawać pytań.', autor: 'Albert Einstein', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Nie czekaj. Pora nigdy nie będzie idealna.', autor: 'Napoleon Hill', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Człowiek tyle jest wart, ile warte są sprawy, którymi się zajmuje.', autor: 'Marek Aureliusz', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Sukces to suma małych wysiłków, powtarzanych dzień po dniu.', autor: 'Robert Collier', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Wielkie rzeczy nigdy nie pochodzą ze strefy komfortu.', autor: 'Roy T. Bennett', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Marzenia są niezbędne do życia.', autor: 'Anais Nin', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Początki są zawsze najtrudniejsze.', autor: 'Paulo Coelho', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Nie możemy zmienić wiatru, ale możemy dostosować żagle.', autor: 'Dolly Parton', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Życie jest tym, co z niego zrobimy.', autor: 'Henry David Thoreau', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Najlepsza zemsta to olbrzymi sukces.', autor: 'Frank Sinatra', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Zawsze dąż do bycia lepszym.', autor: 'Tony Robbins', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Pomyśl, wierz, śnij i odważ się.', autor: 'Walt Disney', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Lecz ci, którzy ufają Panu, nabierają siły, wzbijają się w górę na skrzydłach jak orły, biegną, a nie mdleją, idą, a nie ustają.', autor: 'Izajasza 40:31', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Wiele nieszczęść spotyka sprawiedliwego, ale Pan wyzwala go ze wszystkich.', autor: 'Księga Psalmów 34:19', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Czy nie przykazałem ci: Bądź mocny i mężny? Nie bój się i nie lękaj się, bo Pan, Bóg twój będzie z tobą wszędzie, dokądkolwiek pójdziesz.', autor: 'Jozuego 1:9', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Pójdźcie do mnie wszyscy, którzy jesteście spracowani i obciążeni, a Ja wam dam ukojenie. Weźcie na siebie moje jarzmo i uczcie się ode mnie, że jestem cichy i pokornego serca, a znajdziecie ukojenie dla dusz waszych. Albowiem jarzmo moje jest miłe, a brzemię moje lekkie.', autor: 'Mateusza 11:28–30', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Uniżcie się przed Panem, a wywyższy was.', autor: 'List Jakuba 4:10', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Proście, a będzie wam dane, szukajcie, a znajdziecie; kołaczcie, a otworzą wam. Każdy bowiem, kto prosi, otrzymuje, a kto szuka, znajduje, a kto kołacze, temu otworzą.', autor: 'Mateusza 7:7–8', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'A że sam przeszedł przez cierpienie i próby, może dopomóc tym, którzy przez próby przechodzą.', autor: 'List do Hebrajczyków 2:18', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Nie bój się, bom Ja z tobą, nie lękaj się, bom Ja Bogiem twoim! Wzmocnię cię, a dam ci pomoc, podeprę cię prawicą sprawiedliwości swojej.', autor: 'Izajasza 41:10', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Pan jest mocą i pieśnią moją, i stał się zbawieniem moim. On Bogiem moim, przeto go uwielbiam; On Bogiem ojca mego, przeto go wysławiam.', autor: 'II Ks. Mojżeszowa 15:2', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Bo u Boga żadna rzecz nie jest niemożliwa.', autor: 'Łukasza 1:37', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Wszystko mogę w tym, który mnie wzmacnia, w Chrystusie.', autor: 'List do Filipian 4:13', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Nie bierz na siebie za wiele spraw, bo jeśli będziesz je mnożył, nie unikniesz szkody. I choćbyś pędził, nie dopędzisz, a uciekając nie uciekniesz.', autor: 'Księga Syracha 11,10', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Nie wydawaj duszy swej smutkowi ani nie dręcz siebie myślami. (…) Pociesz swoje serce, i oddal długotrwały smutek od siebie; bo smutek zgubił wielu i nie ma z niego żadnego pożytku.', autor: 'Księga Syracha 30,21-23', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Jedynym sposobem, by pracować naprawdę dobrze jest kochać to, co się robi.', autor: 'Steve Jobs', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Nie możemy stać się tym, kim chcemy być, pozostając tym, kim jesteśmy.', autor: 'Max DePree', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Moc, która leży w Tobie, jest silniejsza od wszystkich przeciwności.', autor: 'Lailah Gifty Akita', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Kiedy napotykasz przeszkody, nie zmieniaj swoich celów; zmień swoje działania.', autor: 'Konfucjusz', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Jeśli marzysz o czymś, czego nigdy nie miałeś, musisz być gotów zrobić coś, czego nigdy nie robiłeś.', autor: 'Thomas Jefferson', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Nigdy nie bój się wyznaczyć sobie zbyt wysokich celów; nawet jeśli nie osiągniesz ich, będziesz miał coś wartościowego.', autor: 'Michał Anioł', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Sukces to nie klucz do szczęścia. Szczęście to klucz do sukcesu.', autor: 'Albert Schweitzer', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Nie ma granic. Istnieją jedynie poziomy, ale nie ma potrzeby zatrzymywać się na nich, lepiej iść dalej.', autor: 'Bruce Lee', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Nie pytaj, czego świat potrzebuje. Zapytaj, co cię ożywia i rób to! Bo to, czego potrzeba światu, to właśnie pełni życia ludzie.', autor: 'Howard Thurman', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Nigdy nie jesteś zbyt stary na to, by zmienić cele lub marzyć nowe marzenia.', autor: 'C.S. Lewis', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Nigdy nie rezygnuj z marzenia tylko dlatego, że jego realizacja zajmie dużo czasu. Czas i tak upłynie.', autor: 'Earl Nightingale', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Przygotowanie to klucz do sukcesu.', autor: 'Alexander Graham Bell', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Najpierw myśl, potem działaj.', autor: 'Konfucjusz', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Sukces polega na tym, aby znać sekret szczęścia.', autor: 'Albert Schweitzer', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Nie pozwól, aby zachowanie innych zniszczyło twój spokój ducha.', autor: 'Dalajlama', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Zrozumienie umysłu oznacza zrozumienie wszystkiego.', autor: 'Dalajlama', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Wszystko, co kochasz, jest związane z ryzykiem.', autor: 'Paulo Coelho', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Najlepszym czasem do sadzenia drzewa było 20 lat temu. Drugim najlepszym czasem jest teraz.', autor: 'Przysłowie chińskie', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Nie pozwól przeszłości posiąść twojego obecnego stanu emocjonalnego.', autor: 'Dalajlama', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Pierwszym krokiem ku sukcesowi zawsze jest decyzja: wchodzę w to!', autor: 'Mark Twain', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Dąż do doskonałości, nigdy do perfekcji.', autor: 'H. Jackson Brown Jr.', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Jeśli nie walczysz o to, czego chcesz, nie płacz za tym, czego nie masz.', autor: 'Swami Vivekananda', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Najlepszy czas na działanie jest teraz.', autor: 'Mark Twain', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Przekuj strach i obawy w motywację do działania.', autor: 'Chris Grosser', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Nigdy nie bój się spróbować czegoś nowego. Pamiętaj, że arka została zbudowana przez amatorów, a Titanic przez profesjonalistów.', autor: 'autor nieznany', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Ciężko pracuj w ciszy, niech twój sukces zrobi hałas.', autor: 'Frank Ocean', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Jeśli nie będziesz ryzykować, nigdy nie zrobisz niczego wartościowego.', autor: 'Denis Waitley', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Czy jesteś na szczycie góry, czy dopiero w drodze na szczyt, krajobraz jest taki sam.', autor: 'autor nieznany', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Podziel się swoim wiedzą. To droga do nieśmiertelności.', autor: 'Dalajlama', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Nie można być zbyt starym na marzenia.', autor: 'autor nieznany', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Nawet najdłuższa podróż zaczyna się od pierwszego kroku.', autor: 'Laozi', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Rzeka przecina skałę nie przez swoją siłę, ale przez upór.', autor: 'H. Jackson Brown Jr.', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Jeśli nie podążasz za swoim marzeniem, ktoś inny cię zatrudni, żebyś pomógł mu spełnić jego marzenia.', autor: 'Dhirubhai Ambani', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Życie to 10% tego, co mi się przydarza i 90% tego, jak na to reaguję.', autor: 'Charles R. Swindoll', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Wymówek szukają nieudacznicy; postępów dokonują zwycięzcy.', autor: 'Brian Tracy', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Wygląd nadrabiaj charakterem, zamiast charakter maskować wyglądem.', autor: 'Brian Tracy', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'W życiu nie ma znaczenia, ile razy zostaniesz rozłożony na łopatki. Liczy się tylko to, ile razy się podniesiesz.', autor: 'Brian Tracy', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Człowiek staje się tym, o czym rozmyśla cały dzień.', autor: 'Brian Tracy', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Jedynymi ludźmi bez problemów są ci na cmentarzu.', autor: 'Tony Robbins', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Tylko ci, którzy nauczyli się mocy szczerego i bezinteresownego wkładu, doświadczają najgłębszej radości życia: prawdziwego spełnienia.', autor: 'Tony Robbins', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Kiedy jesteś wdzięczny, strach znika i pojawia się obfitość.', autor: 'Tony Robbins', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Nigdy nie trać kontroli, spodziewaj się problemów i mimo to idź nadal do przodu.', autor: 'Donald Trump', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Zaskakują mnie ludzie, którzy uważają: Udało mi się, bo jestem taki bystry i pracowałem ciężej niż inni. Przecież jest wielu bystrych i wielu pracuje ciężko! Jeśli odniosłeś sukces, to dlatego, że ktoś po drodze ci pomógł. Był w twoim życiu jakiś świetny nauczyciel. Ktoś pomógł stworzyć ten niesamowity amerykański system, z którego mogłeś korzystać. Ktoś wybudował drogi i mosty. Jeśli masz biznes, nie zbudowałeś go sam. Jesteśmy w tym wszystkim razem.', autor: 'Barack Obama', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Twoją marką jest to, co ludzie mówią o tobie, kiedy wyjdziesz z pokoju.', autor: 'Jeff Bezos', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Cały czas szukaj nowych celów. Nawet jeśli jesteś już bogaty, nawet gdy masz ustabilizowaną firmę. Wciąż pytaj, patrz, szukaj, główkuj, co jeszcze innego można zrobić. To znakomicie wpływa na twoją psychikę, ale także zabezpiecza przed nagłą katastrofą.', autor: 'Ray Kroc', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Pracuj tak ciężko jak to możliwe, to zwiększa szanse na sukces. Jeśli inni ludzie pracują 40 godzin w tygodniu, a ty 100 godzin, to ty w 4 miesiące osiągniesz to, co innym zajmie rok.', autor: 'Elon Musk', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Jesteśmy tutaj, aby przyczynić się do zmiany tego świata. W przeciwnym razie, po co tu jesteśmy?', autor: 'Steve Jobs', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Dążenie do doskonałości jest mniej ekscytujące niż dążenie do rozwoju.', autor: 'Haruki Murakami', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Nie oczekuj, że rzeczy się zmienią, jeśli ty nie zmienisz siebie.', autor: 'Albert Einstein', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Zawsze znajdź powód do uśmiechu.', autor: 'Alice Morse Earle', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Wszystko jest trudne, zanim stanie się łatwe.', autor: 'Johann Wolfgang von Goethe', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Jedyną osobą, z którą powinieneś się ścigać, jesteś ty sam.', autor: 'Oprah Winfrey', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Kiedy jedne drzwi się zamykają, otwierają się inne. Często niepotrzebnie wpatrujemy się w te zamknięte, nie zauważając tych drugich.', autor: 'Helen Keller', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Twoje jutro zależy od wielu dzisiaj.', autor: 'Abraham Lincoln', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Rób to, co możesz, tam, gdzie jesteś, z tym, co masz.', autor: 'Theodore Roosevelt', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Nie możemy pomóc wszystkim, ale wszyscy mogą pomóc komuś.', autor: 'Ronald Reagan', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Jeśli chcesz odnieść sukces, musisz być gotów na to, że inni cię skrytykują. Lęk przed krytyką to jedna z najczęstszych przeszkód na drodze do sukcesu.', autor: 'Grant Cardone', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Nie ma niczego takiego jak brak czasu, to tylko kwestia priorytetów.', autor: 'Alan Lakein', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Wszystko, co naprawdę chcesz, jest po drugiej stronie strachu.', autor: 'George Addair', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Jeżeli myślisz, że możesz coś zrobić, lub myślisz, że nie możesz tego zrobić, masz rację.', autor: 'Henry Ford', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Życie jest jak jazda na rowerze. Aby zachować równowagę, musisz się poruszać.', autor: 'Albert Einstein', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Sukces to ciągłe dążenie do osiągnięcia swoich celów.', autor: 'Jim Rohn', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Największym błędem, jakiego można dokonać, jest bojaźń przed popełnieniem błędów.', autor: 'Elbert Hubbard', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Nie musisz być wielkim, aby zacząć, ale musisz zacząć, żeby być wielkim.', autor: 'Zig Ziglar', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Nie czekaj na doskonałe warunki. Zacznij teraz i skorzystaj z okazji.', autor: 'George Bernard Shaw', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Cokolwiek możesz sobie wyobrazić, możesz to osiągnąć.', autor: 'Napoleon Hill', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Człowiek z wizją zawsze znajdzie sposób, człowiek bez wizji zawsze znajdzie wymówkę.', autor: 'Norman Vincent Peale', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Jeśli nie ryzykujesz, nie masz szansy.', autor: 'Wayne Gretzky', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Jeśli twoje marzenia nie przerażają cię, są za małe.', autor: 'Richard Branson', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Pierwszym krokiem do sukcesu jest decyzja, by nie być przeciętnym.', autor: 'Joe Duncan', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Wszystko zaczyna się od marzeń. Marzenia to dzisiaj myśli, a jutro rzeczywistość.', autor: 'Walt Disney', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Nie liczy się to, ile masz, ale to, co z tego robisz.', autor: 'Bruce Lee', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Zanim coś osiągniesz, musisz czegoś od siebie oczekiwać.', autor: 'Michael Jordan', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Kiedy wygrywasz, nic nie mów, kiedy przegrywasz, mów mniej.', autor: 'Paul Brown', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Najpierw Cię ignorują. Potem śmieją się z Ciebie. Później z Tobą walczą. Później wygrywasz.', autor: 'Mahatma Gandhi', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Ludzie mogą wątpić w to co mówisz, ale uwierzą w to co robisz.', autor: 'Lewis Cass', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Jeśli kiedykolwiek dasz tylko 90% na treningu, to dasz tylko 90%, gdy ma to znaczenie.', autor: 'Michael Owen', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Opory, które przełamujesz fizycznie na siłowni, oraz opory, z którymi walczysz w życiu, mogą jedynie zbudować silny charakter.', autor: 'Arnold Schwarzenegger', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Wytrzymałość można szybko stracić, jeśli przestanie się pracować nad jej utrzymaniem.', autor: 'Bruce Lee', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Trening zajmuje się nie obiektem, ale duchem człowieka i emocjami człowieka.', autor: 'Bruce Lee', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Moje życiowe motto brzmi, że jedynym kalectwem jest w życiu jest negatywne nastawienie.', autor: 'Jessica Long', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Im więcej potu na treningu, tym mniej krwi w boju.', autor: 'Howard E. Wasdin', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Dzisiaj zrobię to, czego inni nie zrobią, więc jutro mogę osiągnąć to, czego inni nie mogą.', autor: 'Jerry Rice', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Postaw swoje cele wysoko i nie przestawaj, aż tam dotrzesz.', autor: 'Bo Jackson', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Czy chciałbyś być człowiekiem, który ogląda jak rzeczy się dzieją, czy człowiekiem, który sprawia, że rzeczy się dzieją?', autor: 'Jim Lovell', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Kiedy z kimś walczę, chcę złamać jego wolę, chcę zabrać jego męskość, chcę wyrwać mu serce i pokazać mu je.', autor: 'Mike Tyson', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Płacz na treningu, śmiej się po wygranej walce.', autor: 'Antoni Gołubiew', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Nasza filozofia jest prosta: walczyć zawsze do końca.', autor: 'Łukasz Żygadło', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Jak trenujesz, tak będziesz walczyć.', autor: 'Bruce Lee', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Zaprzyjaźnij się z bólem, a już nigdy nie będziesz samotny.', autor: 'autor nieznany', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Lataj jak motyl, ukąszaj jak pszczoła.', autor: 'Muhammad Ali', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Trudno pokonać osobę, która nigdy się nie poddaje.', autor: 'Babe Ruth', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Ten, kto zwycięży siebie, jest największym wojownikiem.', autor: 'Richard Kim', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Człowieka można zniszczyć, ale nie pokonać.', autor: 'Ernest Hemingway', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Wojna to pokój. Wolność to niewola. Ignorancja to siła.', autor: 'George Orwell', zrodlo: 'fabrykadygresji.pl' },
  { tresc: '[…] siła nie musi oznaczać przemocy. Żeby być wojownikiem, nie musisz kierować się prawem pięści.', autor: 'Becca Fitzpatrick', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Odejmij własne straty od strat przeciwnika, a jeśli otrzymasz liczbę dodatnią, było to wspaniałe zwycięstwo.', autor: 'Terry Pratchett', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Mistrzowie nie tworzą się na siłowni. Mistrzowie są tworzeni przez coś, co mają głęboko w sobie – pragnienie, marzenie, wizję.', autor: 'Muhammad Ali', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Każdego dnia rób coś, co przybliży cię do lepszego jutra.', autor: 'Doug Firebaugh', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Sukces to nie miejsce, w którym się znajdujesz, ale kierunek, w którym zmierzasz.', autor: 'Oliver Wendell Holmes Jr.', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Jeśli chcesz osiągnąć wielkość, przestań prosić o pozwolenie.', autor: 'autor anonimowy', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Twój czas jest ograniczony, więc nie marnuj go, żyjąc cudzym życiem.', autor: 'Steve Jobs', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'To, czego najbardziej się boisz, jest tym, co musisz zrobić.', autor: 'Tim Ferriss', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Zacznij realizować swoje marzenia! Dopóki tego nie zrobisz, będą sprawiały wrażenie czegoś niewykonalnego.', autor: 'Nelson Mandela', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Większość ludzi rezygnuje zanim uda się im odnieść sukces. Nie rezygnuj, bo nigdy nie wiesz, czy następna próba nie przyniesie ci sukcesu.', autor: 'Bill Gates', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Jest tylko jedno szczęście w życiu – kochać i być kochanym.', autor: 'George Sand', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Rób to, co uważasz za właściwe. I tak nie unikniesz krytyki.', autor: 'Eleanor Roosevelt', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Najlepsza zemsta to sukces i dobre życie.', autor: 'Meryl Streep', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Pomyślność to zdolność do doceniania tego, co masz, zamiast zawsze dążyć do posiadania więcej.', autor: 'Jon Kabat-Zinn', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Najlepszy czas na działanie jest teraz.', autor: 'Mark Fisher', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Zmień myślenie, a zmienisz swoje życie.', autor: 'Brian Tracy', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Nie licz dni, spraw, aby dni się liczyły.', autor: 'Muhammad Ali', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Nie pozwól, by trudności wczorajszego dnia wpływały na jasność dzisiejszego.', autor: 'Chetan Bhagat', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Błędy to część opłaty, jaką musisz zapłacić za pełne doświadczenie życia.', autor: 'Sophia Loren', zrodlo: 'fabrykadygresji.pl (via vogue.pl)' },
  { tresc: 'Wielkie rzeczy nie powstają w wyniku impulsu, a w wyniku składania małych rzeczy w jedną całość.', autor: 'Vincent Van Gogh', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Nasze życie jest takim, jakim uczyniły je nasze myśli.', autor: 'Marek Aureliusz', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Nic nie jest niemożliwe. Samo słowo mówi, że jestem możliwa.', autor: 'Audrey Hepburn', zrodlo: 'fabrykadygresji.pl (via vogue.pl)' },
  { tresc: 'Ważne jest, aby nigdy nie przestać pytać.', autor: 'Albert Einstein', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Największym niebezpieczeństwem dla większości z nas nie jest to, że mierzymy za wysoko i nie osiągamy celu, ale to, że mierzymy za nisko i cel osiągamy.', autor: 'Michał Anioł Buonarroti', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Człowiek jest tym, o czym przez cały dzień myśli.', autor: 'Ralph Waldo Emerson', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Skoro można pomyśleć, że może być lepiej, to znaczy, że już jest lepiej.', autor: 'Olga Tokarczuk', zrodlo: 'fabrykadygresji.pl (via vogue.pl)' },
  { tresc: 'Wizja bez działania to marzenie. Działanie bez wizji to koszmar.', autor: 'przysłowie japońskie', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Sukces to robienie zwykłych rzeczy – niezwykle dobrze.', autor: 'Jim Rohn', zrodlo: 'fabrykadygresji.pl' },
  { tresc: 'Nie musisz widzieć całych schodów. Uczyń tylko pierwszy krok.', autor: 'Martin Luther King Jr.', zrodlo: 'fabrykadygresji.pl' },
];
// 107 komunikatow, zrodlo: docs/data/marquee-komunikaty.csv (Runda #18)
const PIPBOY_MARQUEE = [
  { tresc: 'Kreatyna czeka. Dziś priorytet: z posiłkiem, nie na czczo.', kategoria: 'suplementy', warunek: 'dzien_treningowy=nie AND kreatyna_zaznaczona=nie', priorytet: 2 },
  { tresc: 'Vita Pak, Kolagen, Omega 3 — trzy małe kroki, jeden odhaczony dzień.', kategoria: 'suplementy', warunek: 'pora=rano AND suplementy_rdzenne_procent<100', priorytet: 2 },
  { tresc: 'Melatonina jest tu, gdy jej potrzebujesz. Nie wcześniej.', kategoria: 'suplementy', warunek: 'pora=wieczor', priorytet: 1 },
  { tresc: 'Gainer czeka zaraz po treningu — nie zostawiaj go na później.', kategoria: 'suplementy', warunek: 'dzien_treningowy=tak AND trening_zakonczony=tak AND gainer_zaznaczony=nie', priorytet: 2 },
  { tresc: 'Nawodnienie to nie szczegół — to fundament reszty dnia.', kategoria: 'suplementy', warunek: 'pora=popoludnie AND nawodnienie_zaznaczone=nie', priorytet: 1 },
  { tresc: 'Sto dni suplementacji zaczyna się od jednego zaznaczonego dziś.', kategoria: 'suplementy', warunek: 'streak_suplementy=0', priorytet: 1 },
  { tresc: 'Posiłek 1: dziś stawiasz na białko, nie na przypadek.', kategoria: 'dieta', warunek: 'posilek=1 AND wykonany=nie', priorytet: 2 },
  { tresc: 'Kolejny posiłek, kolejny punkt dla Dyscypliny.', kategoria: 'dieta', warunek: 'pora_posilku_zbliza_sie=tak', priorytet: 1 },
  { tresc: 'Gainer to nie dodatek — w dzień treningowy to pełnoprawny posiłek.', kategoria: 'dieta', warunek: 'dzien_treningowy=tak', priorytet: 1 },
  { tresc: 'Zjedz coś lekkiego przed treningiem — żołądek podziękuje później.', kategoria: 'dieta', warunek: 'dzien_treningowy=tak AND godzina<trening_start-1h', priorytet: 1 },
  { tresc: '5 posiłków. Nie liczysz kalorii, liczysz obecność.', kategoria: 'dieta', warunek: 'pora=poludnie', priorytet: 1 },
  { tresc: 'Aldi ma dziś nową gazetkę — sprawdź, zanim wyjdziesz.', kategoria: 'dieta', warunek: 'dzien_zakupowy=tak', priorytet: 1 },
  { tresc: 'Za chwilę trening. Ciało pamięta więcej, niż myślisz.', kategoria: 'trening', warunek: 'dzien_treningowy=tak AND godzina<trening_start-30min', priorytet: 2 },
  { tresc: 'Trzy sesje bez progresu na tym ćwiczeniu? To sygnał, nie porażka.', kategoria: 'trening', warunek: 'plateau_aktywny=tak', priorytet: 3 },
  { tresc: 'Nowy rekord czeka na te same serie, które robisz co tydzień.', kategoria: 'trening', warunek: 'dzien_treningowy=tak AND trening_typ=plan-AB', priorytet: 1 },
  { tresc: 'Rozgrzewka to nie formalność — to bilet wstępu do reszty sesji.', kategoria: 'trening', warunek: 'trening_w_toku=tak AND rozgrzewka_zaznaczona=nie', priorytet: 2 },
  { tresc: 'Zły dzień na trening pełną parą? Zmodyfikowany też się liczy.', kategoria: 'trening', warunek: 'dzien_treningowy=tak AND mood_rano<=4', priorytet: 2 },
  { tresc: 'Kettle po treningu pracuje na biodra, których jeszcze nie znasz.', kategoria: 'trening', warunek: 'trening_w_toku=tak AND etap=kardio', priorytet: 1 },
  { tresc: '1h15 dziś należy do Ciebie. Reszta poczeka.', kategoria: 'trening', warunek: 'dzien_treningowy=tak AND godzina=trening_start', priorytet: 2 },
  { tresc: 'Osiem tygodni FBW za Tobą — czas na przegląd, nie na rutynę.', kategoria: 'trening', warunek: 'tydzien_planu=8', priorytet: 2 },
  { tresc: 'Za godzinę gasną światła — telefon już może zwolnić tempo.', kategoria: 'sen', warunek: 'godzina=cisza_nocna-1h', priorytet: 2 },
  { tresc: 'Ekran teraz to pożyczka od jutrzejszej koncentracji.', kategoria: 'sen', warunek: 'pora=wieczor AND higiena_swiatla_zaznaczona=nie', priorytet: 2 },
  { tresc: 'Dzień B kończy się późno — dziś sen jest ważniejszy niż jeszcze jeden odcinek.', kategoria: 'sen', warunek: 'typ_dnia=B AND godzina>20:00', priorytet: 1 },
  { tresc: 'Siedem do dziewięciu godzin. Reszta to szczegóły.', kategoria: 'sen', warunek: 'pora=wieczor', priorytet: 1 },
  { tresc: 'Rytm zmianowy szanuje regularność bardziej niż długość snu jednej nocy.', kategoria: 'sen', warunek: 'typ_dnia_zmienil_sie=tak', priorytet: 1 },
  { tresc: 'Jak się obudziłeś, tak zaczyna się cała reszta dnia — zapisz to szczerze.', kategoria: 'mood', warunek: 'pora=rano AND mood_rano_wypelniony=nie', priorytet: 2 },
  { tresc: 'Wieczorny check to nie ocena dnia — to dane dla jutra.', kategoria: 'mood', warunek: 'pora=wieczor AND mood_wieczor_wypelniony=nie', priorytet: 2 },
  { tresc: 'Brzuch mówi coś ważnego — zapisz, co jadłeś ostatnie 48h.', kategoria: 'mood', warunek: 'gi_wynik<=4', priorytet: 3 },
  { tresc: 'Skupienie dziś niżej niż zwykle? To też jest informacja, nie wyrok.', kategoria: 'mood', warunek: 'skupienie<=4', priorytet: 1 },
  { tresc: 'Cztery kategorie rano, pięć wieczorem — mniej niż minuta, więcej niż zgadywanie.', kategoria: 'mood', warunek: 'pora=rano_lub_wieczor', priorytet: 1 },
  { tresc: 'Dziesięć minut czytania to już więcej niż zero.', kategoria: 'czytelnictwo', warunek: 'minuty_dzis=0 AND godzina>18:00', priorytet: 2 },
  { tresc: 'Audiobook i dojazd do pracy pasują do siebie lepiej niż myślisz.', kategoria: 'czytelnictwo', warunek: 'dojazd_w_toku=tak', priorytet: 1 },
  { tresc: 'Średnia tygodniowa trzyma się dobrze — dzisiejsze 20 minut to nie porażka.', kategoria: 'czytelnictwo', warunek: 'minuty_dzis<60 AND srednia_7dni>=55', priorytet: 1 },
  { tresc: 'Skończona książka to nie tylko odznaka — to dowód, że dowozisz.', kategoria: 'czytelnictwo', warunek: 'strona_ostatnia=tak', priorytet: 1 },
  { tresc: 'Krem do twarzy czeka w tym samym miejscu co zawsze — 15 sekund, nie 15 minut.', kategoria: 'pielegnacja', warunek: 'slot_poranny_aktywny=tak', priorytet: 1 },
  { tresc: 'Środa i niedziela to dni Nizoralu — dziś jeden z nich.', kategoria: 'pielegnacja', warunek: 'dzien_tygodnia=sroda_lub_niedziela', priorytet: 2 },
  { tresc: 'Fryzjer czeka od trzech tygodni — to już nie przypomnienie, to termin.', kategoria: 'pielegnacja', warunek: 'dni_od_fryzjera>=21', priorytet: 2 },
  { tresc: 'Ręce dwa razy dziennie, twarz rano i wieczorem — bez presji, ale bez zapominania.', kategoria: 'pielegnacja', warunek: 'pora=dowolna', priorytet: 1 },
  { tresc: 'Łazienka dziś czeka na Ciebie — reszta stref poczeka do swojego dnia.', kategoria: 'sprzatanie', warunek: 'strefa_dnia=lazienka', priorytet: 1 },
  { tresc: 'Piętnaście minut w tagu #sprzątanie to floor, nie sufit.', kategoria: 'sprzatanie', warunek: 'czas_sprzatania_dzis<15 AND godzina>18:00', priorytet: 2 },
  { tresc: 'Robot zrobił podłogi — Ty zajmij się tym, czego on nie widzi.', kategoria: 'sprzatanie', warunek: 'robot_zakonczyl_cykl=tak', priorytet: 1 },
  { tresc: 'Filtr robota czeka na czyszczenie raz w miesiącu — dziś może być ten dzień.', kategoria: 'sprzatanie', warunek: 'dni_od_czyszczenia_robota>=30', priorytet: 1 },
  { tresc: 'Pies czeka przy drzwiach — to też jest kontakt z naturą.', kategoria: 'spacer_natura', warunek: 'pora=popoludnie AND spacery_dzis=0', priorytet: 1 },
  { tresc: 'Trzy dni bez wyjścia na zewnątrz — organizm to zauważa, nawet jeśli Ty nie.', kategoria: 'spacer_natura', warunek: 'dni_bez_natury>=3', priorytet: 2 },
  { tresc: 'Statyw stoi przy stanowisku nie bez powodu — dziś też może nagrywać.', kategoria: 'portfolio', warunek: 'sesja_malarska_w_toku=tak AND nagrywanie_aktywne=nie', priorytet: 2 },
  { tresc: 'Zdjęcie zrobione to połowa checklisty. Opis i publikacja czekają na drugą.', kategoria: 'portfolio', warunek: 'projekt_ukonczony=tak AND checklist_publikacji<100', priorytet: 2 },
  { tresc: 'Regularność bije tempo — trzy posty tygodniowo przez rok, nie siedem przez miesiąc.', kategoria: 'portfolio', warunek: 'tydzien_bez_publikacji=tak', priorytet: 1 },
  { tresc: 'Kolorowanka też się liczy jako trening ręki i oka.', kategoria: 'portfolio', warunek: 'czas_wolny_aktywny=tak', priorytet: 1 },
  { tresc: 'Trend marki w tym tygodniu spada — to sygnał, nie kara.', kategoria: 'portfolio', warunek: 'rolling_average_portfolio_spada=tak', priorytet: 2 },
  { tresc: 'Pierwsza publikacja niezależna od Neon Forge Studio to inny rodzaj kamienia milowego.', kategoria: 'portfolio', warunek: 'pierwsze_zlecenie_niezalezne=tak', priorytet: 3 },
  { tresc: 'Reddit i Discord płacą się uwagą, nie ogłoszeniami — dziś warto tylko poczytać.', kategoria: 'portfolio', warunek: 'pora=wieczor AND dzien_publikacji=nie', priorytet: 1 },
  { tresc: 'Putty & Paint czeka z inną publicznością niż Instagram.', kategoria: 'portfolio', warunek: 'kanal_putty_paint_aktywny=tak', priorytet: 1 },
  { tresc: 'HP na dziś zaczyna się od zera złych decyzji — masz pełną pulę.', kategoria: 'hp_ogolne', warunek: 'pora=rano', priorytet: 1 },
  { tresc: 'Piętnaście minut do zamknięcia dnia — sprawdź, co jeszcze czeka.', kategoria: 'hp_ogolne', warunek: 'godzina=cisza_nocna-15min AND dzien_niedomkniety=tak', priorytet: 3 },
  { tresc: 'Perfect Day nie wymaga perfekcji — wymaga domknięcia listy.', kategoria: 'hp_ogolne', warunek: 'procent_dnia>=90', priorytet: 1 },
  { tresc: 'Atrybut Ciało rośnie wolniej niż Dyscyplina w tym tygodniu — to tylko obserwacja.', kategoria: 'hp_ogolne', warunek: 'atrybut_najslabszy=cialo', priorytet: 1 },
  { tresc: 'Streak siedmiu dni jest bliżej, niż się wydaje.', kategoria: 'hp_ogolne', warunek: 'streak_aktualny=6', priorytet: 2 },
  { tresc: 'Dolina cienia w historii postaci to dowód, że wracasz, nie że przegrywasz.', kategoria: 'hp_ogolne', warunek: 'smierc_wystapila_wczoraj=tak', priorytet: 2 },
  { tresc: 'GOD_MODE_24H nadal aktywny — przypomnienia zostają, presja nie.', kategoria: 'god_mode', warunek: 'god_mode_aktywny=tak', priorytet: 1 },
  { tresc: 'Dwa dni ochronne z rzędu — Tryb Regeneracji czeka na Twoją decyzję.', kategoria: 'god_mode', warunek: 'dni_god_mode_z_rzedu=2', priorytet: 3 },
  { tresc: 'W Trybie Regeneracji liczy się powrót, nie tempo.', kategoria: 'god_mode', warunek: 'tryb_regeneracji_aktywny=tak', priorytet: 1 },
  { tresc: 'Trzy aktywacje w tym miesiącu — jedna jeszcze zostaje, jeśli będzie potrzebna.', kategoria: 'god_mode', warunek: 'aktywacje_w_miesiacu=3', priorytet: 1 },
  { tresc: 'Setka Perfect Days nie bierze się z jednego dobrego tygodnia.', kategoria: 'odznaki', warunek: 'perfect_days_total>=90', priorytet: 1 },
  { tresc: 'Feniks czeka na tych, którzy wracają po zerwanym streaku — nie na tych, którzy nie upadają.', kategoria: 'odznaki', warunek: 'streak_zerwany_ostatnio=tak', priorytet: 2 },
  { tresc: 'Sekretna odznaka nie pokazuje się na liście — pojawi się, kiedy na nią zapracujesz.', kategoria: 'odznaki', warunek: 'pora=dowolna', priorytet: 1 },
  { tresc: 'Poziom 10 to połowa drogi na krzywej, którą sam sobie wybrałeś.', kategoria: 'odznaki', warunek: 'poziom_postaci=9', priorytet: 1 },
  { tresc: 'Przegląd auta czeka od miesiąca — poziomy płynów same się nie sprawdzą.', kategoria: 'pojazdy', warunek: 'dni_od_przegladu_auta>=30', priorytet: 1 },
  { tresc: 'Wiosna budzi motocykl z zimowego snu — akumulator i opony najpierw.', kategoria: 'pojazdy', warunek: 'sezon=wiosna AND motocykl_przygotowany=nie', priorytet: 2 },
  { tresc: 'Łańcuch i ciśnienie w oponach — trzydzieści dni minęło od ostatniej kontroli.', kategoria: 'pojazdy', warunek: 'dni_od_kontroli_motocykla>=30 AND sezon_motocyklowy=tak', priorytet: 1 },
  { tresc: 'Jesień to sygnał, żeby odłożyć motocykl porządnie, nie na chybił trafił.', kategoria: 'pojazdy', warunek: 'sezon=jesien AND motocykl_odlozony=nie', priorytet: 2 },
  { tresc: '70% sprawdzone, 30% nowe — dziś lista zakupów ma dla Ciebie propozycję.', kategoria: 'zakupy', warunek: 'dzien_zakupowy=tak', priorytet: 1 },
  { tresc: 'Tofu zamiast kurczaka raz na tydzień nie zaszkodzi rutynie.', kategoria: 'zakupy', warunek: 'kategoria_rotacyjna_dostepna=tak', priorytet: 1 },
  { tresc: 'Kwartał minął — to dobry moment, żeby pomyśleć o badaniach kontrolnych.', kategoria: 'badania', warunek: 'dni_od_ostatnich_badan>=90', priorytet: 1 },
  { tresc: 'Kontrola nie musi być pilna, żeby być ważna.', kategoria: 'badania', warunek: 'reminder_kwartalny_aktywny=tak', priorytet: 1 },
  { tresc: 'Dziesięć minut rozciągania zaraz po przebudzeniu — zanim dzień nabierze tempa.', kategoria: 'rozciaganie', warunek: 'pora=rano AND rozciaganie_zaznaczone=nie', priorytet: 2 },
  { tresc: 'Pielęgnacja się nie odbyła? Rozciąganie i tak czeka w tym samym miejscu.', kategoria: 'rozciaganie', warunek: 'pielegnacja_poranna=nie AND rozciaganie_zaznaczone=nie', priorytet: 2 },
  { tresc: 'Czas wolny nie potrzebuje uzasadnienia — należy Ci się po prostu dlatego, że domknąłeś dzień.', kategoria: 'czas_wolny', warunek: 'wszystkie_obowiazkowe_zrobione=tak', priorytet: 1 },
  { tresc: 'Nic nierobienie to też pozycja w harmonogramie, nie luka w nim.', kategoria: 'czas_wolny', warunek: 'czas_wolny_aktywny=tak', priorytet: 1 },
  { tresc: 'Dzień skompresowany przez nadgodziny? Wydłużony sen liczy się bardziej niż zaległy odcinek.', kategoria: 'czas_wolny', warunek: 'dzien_skompresowany=tak', priorytet: 2 },
  { tresc: 'Dzień dobry. System czeka, żebyś zaczął dzień na swoich warunkach.', kategoria: 'ogolne', warunek: 'pora=start_dnia', priorytet: 1 },
  { tresc: 'Nadgodziny przesunęły popołudnie — HP tego nie zauważy.', kategoria: 'ogolne', warunek: 'nadgodziny_wykryte=tak', priorytet: 1 },
  { tresc: 'Kalendarz zaktualizował się sam — sprawdź, czy godziny się zgadzają.', kategoria: 'ogolne', warunek: 'sync_kalendarza_wykonany=tak', priorytet: 1 },
  { tresc: 'Dzień się kończy. To, co zostało niedomknięte, zaczeka do jutra bez odsetek.', kategoria: 'ogolne', warunek: 'godzina=cisza_nocna', priorytet: 1 },
  { tresc: 'Grafik na przyszły miesiąc jeszcze nie doszedł — czas przypomnieć pracodawcy.', kategoria: 'ogolne', warunek: 'dzien_miesiaca=ostatni', priorytet: 2 },
  { tresc: 'Niedzielny przegląd trwa piętnaście minut i mówi więcej niż tydzień domysłów.', kategoria: 'ogolne', warunek: 'dzien_tygodnia=niedziela AND godzina=13:00', priorytet: 2 },
  { tresc: 'Trend, nie pojedynczy dzień, mówi prawdę o tym, jak Ci idzie.', kategoria: 'ogolne', warunek: 'widok=dashboard', priorytet: 1 },
  { tresc: 'Rok z systemem nie liczy się jakością, tylko samym faktem, że nadal tu jesteś.', kategoria: 'ogolne', warunek: 'dni_od_startu=365', priorytet: 1 },
  { tresc: 'Poduszka bezpieczeństwa rośnie po trochu, nie od razu.', kategoria: 'finanse', warunek: 'modul_21_aktywny=tak', priorytet: 1 },
  { tresc: 'Rezerwa podatkowa i rezerwa osobista to dwa różne cele — oba warte pilnowania.', kategoria: 'finanse', warunek: 'modul_21_aktywny=tak AND przeglad_miesieczny=tak', priorytet: 1 },
  { tresc: 'Licznik, nie checkbox — dziś warto zerknąć, ile realnie odłożone.', kategoria: 'finanse', warunek: 'modul_21_aktywny=tak AND dzien_miesiaca=1', priorytet: 1 },
  { tresc: 'Trzy posiłki za Tobą, dwa przed Tobą — dzień trzyma się planu.', kategoria: 'dieta', warunek: 'posilki_wykonane=3', priorytet: 1 },
  { tresc: 'Białko w pierwszym posiłku pracuje na skupienie, nie tylko na mięśnie.', kategoria: 'dieta', warunek: 'posilek=1', priorytet: 1 },
  { tresc: 'Kolejna seria, ten sam ciężar, inny dzień — progres bywa cichy.', kategoria: 'trening', warunek: 'trening_w_toku=tak AND seria_bez_progresu=tak', priorytet: 1 },
  { tresc: 'Mobilność barków i bioder dziś pracuje na coś, czego jeszcze nie zacząłeś.', kategoria: 'trening', warunek: 'etap=kardio_mobilnosc', priorytet: 1 },
  { tresc: 'Higiena światła to jedyny obowiązkowy punkt wieczoru, który nie wymaga wysiłku.', kategoria: 'sen', warunek: 'pora=wieczor AND higiena_swiatla_zaznaczona=nie', priorytet: 2 },
  { tresc: 'Dwa wpisy dziennie budują obraz, którego jeden nigdy by nie pokazał.', kategoria: 'mood', warunek: 'liczba_wpisow_dzis=1', priorytet: 1 },
  { tresc: 'Setka spacerów bez jednego przypomnienia — to Twoja własna konsekwencja, nie systemowa.', kategoria: 'spacer_natura', warunek: 'spacery_total>=100', priorytet: 1 },
  { tresc: 'Kwadrat na liście sprzątania nie musi być idealny — musi być zrobiony.', kategoria: 'sprzatanie', warunek: 'strefa_dnia_aktywna=tak', priorytet: 1 },
  { tresc: 'Trzy wystąpienia tego ćwiczenia bez progresu — może czas na zamianę, nie na upór.', kategoria: 'trening', warunek: 'wystapienia_bez_progresu=3', priorytet: 3 },
  { tresc: 'RCP zaktualizował dzisiejszy koniec pracy — popołudnie przesunęło się razem z nim.', kategoria: 'ogolne', warunek: 'rcp_odczyt_wykonany=tak', priorytet: 1 },
  { tresc: 'Cotygodniowy eksport danych właśnie się zakończył — miesiące pracy mają teraz kopię.', kategoria: 'ogolne', warunek: 'backup_wykonany=tak', priorytet: 1 },
  { tresc: 'Cytat na dziś już czeka na pierwszym ekranie — czasem to wystarczy na start.', kategoria: 'ogolne', warunek: 'pora=start_dnia', priorytet: 1 },
  { tresc: 'Konflikt zapisu wykryty między telefonem a komputerem — nowsza wersja wygrała, reszta widoczna w historii.', kategoria: 'ogolne', warunek: 'konflikt_sync_wykryty=tak', priorytet: 2 },
  { tresc: 'Onboarding to jednorazowa rozmowa z systemem — reszta już się dzieje sama.', kategoria: 'ogolne', warunek: 'pierwsze_uruchomienie=tak', priorytet: 1 },
  { tresc: 'Dashboard pokazuje więcej niż dzisiejszy dzień — czasem warto spojrzeć szerzej.', kategoria: 'ogolne', warunek: 'widok=dashboard AND wizyt_w_tygodniu=1', priorytet: 1 },
  { tresc: 'Token wykorzystany mądrze to nie porażka — to dokładnie to, po co powstał.', kategoria: 'god_mode', warunek: 'god_mode_uzyty_dzis=tak', priorytet: 1 },
  { tresc: 'Pięć Atrybutów, jeden dzień — nie muszą rosnąć równo, żeby się liczyć.', kategoria: 'hp_ogolne', warunek: 'widok=karta_postaci', priorytet: 1 },
];

// ---- Moduł 2: Trening — plan startowy A/B (sekcja 2, do wpisania jako punkt
// wyjścia edytowalnego planu w arkuszu Plan_Treningowy — Runda #17) ----
const PIPBOY_TRENING_PLAN_STARTOWY = {
  A: [
    { cwiczenie: 'Przysiad ze sztangą', serie: 3, powtorzenia: '8-10', przerwa_sek: 90 },
    { cwiczenie: 'Wyciskanie sztangi na ławce płaskiej', serie: 3, powtorzenia: '8-10', przerwa_sek: 90 },
    { cwiczenie: 'Wiosłowanie sztangą w opadzie', serie: 3, powtorzenia: '8-10', przerwa_sek: 90 },
    { cwiczenie: 'Wyciskanie hantli nad głowę (stojąc)', serie: 2, powtorzenia: '10-12', przerwa_sek: 60 },
    { cwiczenie: 'Plank', serie: 3, powtorzenia: '30-45 sek', przerwa_sek: 45 },
  ],
  B: [
    { cwiczenie: 'Martwy ciąg rumuński', serie: 3, powtorzenia: '8-10', przerwa_sek: 90 },
    { cwiczenie: 'Wyciskanie hantli na ławce skośnej', serie: 3, powtorzenia: '10-12', przerwa_sek: 60 },
    { cwiczenie: 'Wiosłowanie hantlą jednorącz', serie: 3, powtorzenia: '10-12', przerwa_sek: 60 },
    { cwiczenie: 'Wyciskanie sztangi nad głowę (OHP)', serie: 2, powtorzenia: '12', przerwa_sek: 45 },
    { cwiczenie: 'Dead bug', serie: 3, powtorzenia: '8-10 / stronę', przerwa_sek: 45 },
  ],
};
// Rotacja: Tydzień 1: Wt=A, Czw=B, Sob=A. Tydzień 2: Wt=B, Czw=A, Sob=B. (ciągła A-B-A-B...)

// ---- Sekcja 4.2: punkty zdobywane (przypisane do Atrybutów) ----
const PIPBOY_PUNKTY_ZDOBYTE = {
  suplement_rdzenny: { punkty: 1, atrybut: 'dyscyplina' },
  posilek: { punkty: 2, atrybut: 'dyscyplina' },
  trening_ukonczony: { punkty: 20, atrybut: 'cialo' },
  progresja_ciezaru: { punkty: 10, atrybut: 'cialo' },
  rozciaganie: { punkty: 5, atrybut: 'cialo' },
  mood_wpis: { punkty: 3, atrybut: 'umysl', max_dziennie: 6 },
  pielegnacja_pozycja: { punkty: 2, atrybut: 'dyscyplina' },
  higiena_swiatla: { punkty: 3, atrybut: 'umysl' },
};
const PIPBOY_ATRYBUTY = ['cialo', 'umysl', 'dyscyplina', 'otoczenie', 'personal_brand'];

// 208 odznak — pelna lista, sekcja 4.3 dokumentu koncepcyjnego (Runda #9)
const PIPBOY_ODZNAKI = [
  { id: 1, typ: 'S', kategoria: 'A', kategoriaNazwa: 'SUPLEMENTACJA / DYSCYPLINA', nazwa: 'Pierwszy krok', opis: 'pierwszy dzień z pełną suplementacją rdzenną' },
  { id: 2, typ: 'Z', kategoria: 'A', kategoriaNazwa: 'SUPLEMENTACJA / DYSCYPLINA', nazwa: 'Tydzień rutyny', opis: '7 dni z rzędu 100% suplementów rdzennych' },
  { id: 3, typ: 'S', kategoria: 'A', kategoriaNazwa: 'SUPLEMENTACJA / DYSCYPLINA', nazwa: 'Miesiąc dyscypliny', opis: '30 dni z rzędu 100% suplementów rdzennych' },
  { id: 4, typ: 'S', kategoria: 'A', kategoriaNazwa: 'SUPLEMENTACJA / DYSCYPLINA', nazwa: 'Kwartał żelaznej woli', opis: '90 dni z rzędu' },
  { id: 5, typ: 'S', kategoria: 'A', kategoriaNazwa: 'SUPLEMENTACJA / DYSCYPLINA', nazwa: 'Pół roku nawyku', opis: '180 dni z rzędu' },
  { id: 6, typ: 'S', kategoria: 'A', kategoriaNazwa: 'SUPLEMENTACJA / DYSCYPLINA', nazwa: 'Rok konsekwencji', opis: '365 dni z rzędu' },
  { id: 7, typ: 'S', kategoria: 'A', kategoriaNazwa: 'SUPLEMENTACJA / DYSCYPLINA', nazwa: 'Setka', opis: '100 dni łącznie z pełną suplementacją (niekoniecznie z rzędu)' },
  { id: 8, typ: 'S', kategoria: 'A', kategoriaNazwa: 'SUPLEMENTACJA / DYSCYPLINA', nazwa: 'Pięćsetka', opis: '500 dni łącznie' },
  { id: 9, typ: 'Z', kategoria: 'A', kategoriaNazwa: 'SUPLEMENTACJA / DYSCYPLINA', nazwa: 'Odzyskany rytm', opis: 'powrót do 100% po przerwie 3+ dni' },
  { id: 10, typ: 'S', kategoria: 'A', kategoriaNazwa: 'SUPLEMENTACJA / DYSCYPLINA', nazwa: 'Świadomy wybór', opis: 'pierwsze użycie Melatoniny "tylko w razie potrzeby" bez nadużycia (miesiąc bez przekroczenia limitu)' },
  { id: 11, typ: 'S', kategoria: 'A', kategoriaNazwa: 'SUPLEMENTACJA / DYSCYPLINA', nazwa: 'Nawodniony', opis: '30 dni z rzędu zaznaczonego nawodnienia' },
  { id: 12, typ: 'S', kategoria: 'A', kategoriaNazwa: 'SUPLEMENTACJA / DYSCYPLINA', nazwa: 'Kreatyna bez ryzyka', opis: '60 dni świadomego dopasowania pory kreatyny bez epizodu GI' },
  { id: 13, typ: 'Z', kategoria: 'A', kategoriaNazwa: 'SUPLEMENTACJA / DYSCYPLINA', nazwa: 'Perfekcyjny tydzień suplementów', opis: '7/7 dni, wszystkie pozycje rdzenne' },
  { id: 14, typ: 'S', kategoria: 'A', kategoriaNazwa: 'SUPLEMENTACJA / DYSCYPLINA', nazwa: 'Gainer na czas', opis: '20 sesji treningowych z gainerem przyjętym zaraz po treningu' },
  { id: 15, typ: 'S', kategoria: 'A', kategoriaNazwa: 'SUPLEMENTACJA / DYSCYPLINA', nazwa: 'Sekretna: Fundament', opis: 'odblokowana po 6 miesiącach systemu, niezależnie od streaków (nagroda za sam fakt wytrwania z systemem)' },
  { id: 16, typ: 'S', kategoria: 'B', kategoriaNazwa: 'TRENING / CIAŁO', nazwa: 'Powrót na matę', opis: 'pierwszy trening FBW po rozpoczęciu systemu' },
  { id: 17, typ: 'Z', kategoria: 'B', kategoriaNazwa: 'TRENING / CIAŁO', nazwa: 'Tydzień w rytmie', opis: '3 treningi w tygodniu, tydzień z rzędu' },
  { id: 18, typ: 'S', kategoria: 'B', kategoriaNazwa: 'TRENING / CIAŁO', nazwa: 'Miesiąc w budowie', opis: '12 treningów w 30 dni' },
  { id: 19, typ: 'S', kategoria: 'B', kategoriaNazwa: 'TRENING / CIAŁO', nazwa: 'Kwartał regularności', opis: '~36 treningów w 90 dni' },
  { id: 20, typ: 'S', kategoria: 'B', kategoriaNazwa: 'TRENING / CIAŁO', nazwa: 'Pół roku w budowie', opis: '~78 treningów w 180 dni' },
  { id: 21, typ: 'S', kategoria: 'B', kategoriaNazwa: 'TRENING / CIAŁO', nazwa: 'Setka treningów', opis: '100 ukończonych sesji FBW łącznie' },
  { id: 22, typ: 'S', kategoria: 'B', kategoriaNazwa: 'TRENING / CIAŁO', nazwa: 'Dwieście treningów', opis: '200 sesji łącznie' },
  { id: 23, typ: 'S', kategoria: 'B', kategoriaNazwa: 'TRENING / CIAŁO', nazwa: 'Pierwszy rekord', opis: 'pierwsza zanotowana progresja ciężaru (dowolne ćwiczenie)' },
  { id: 24, typ: 'S', kategoria: 'B', kategoriaNazwa: 'TRENING / CIAŁO', nazwa: 'Dziesięć rekordów', opis: '10 progresji ciężaru łącznie' },
  { id: 25, typ: 'S', kategoria: 'B', kategoriaNazwa: 'TRENING / CIAŁO', nazwa: 'Pięćdziesiąt rekordów', opis: '50 progresji łącznie' },
  { id: 26, typ: 'S', kategoria: 'B', kategoriaNazwa: 'TRENING / CIAŁO', nazwa: 'Przełamanie plateau', opis: 'pierwsza progresja po zarejestrowanym 3-sesyjnym plateau' },
  { id: 27, typ: 'S', kategoria: 'B', kategoriaNazwa: 'TRENING / CIAŁO', nazwa: 'Mistrz przysiadu', opis: '10 progresji w przysiadzie ze sztangą' },
  { id: 28, typ: 'S', kategoria: 'B', kategoriaNazwa: 'TRENING / CIAŁO', nazwa: 'Mistrz wyciskania', opis: '10 progresji w wyciskaniu (płaskim lub skośnym)' },
  { id: 29, typ: 'S', kategoria: 'B', kategoriaNazwa: 'TRENING / CIAŁO', nazwa: 'Mistrz martwego ciągu', opis: '10 progresji w martwym ciągu rumuńskim' },
  { id: 30, typ: 'S', kategoria: 'B', kategoriaNazwa: 'TRENING / CIAŁO', nazwa: 'Żelazne barki', opis: '10 progresji w OHP/wyciskaniu nad głowę' },
  { id: 31, typ: 'S', kategoria: 'B', kategoriaNazwa: 'TRENING / CIAŁO', nazwa: 'Rdzeń stalowy', opis: '20 ukończonych sesji plank/dead bug bez skrócenia czasu' },
  { id: 32, typ: 'Z', kategoria: 'B', kategoriaNazwa: 'TRENING / CIAŁO', nazwa: 'Perfekcyjny tydzień treningowy', opis: 'wszystkie 3 zaplanowane treningi + kardio + rozciąganie' },
  { id: 33, typ: 'S', kategoria: 'B', kategoriaNazwa: 'TRENING / CIAŁO', nazwa: 'Trzy miesiące bez przerwy dłuższej niż tydzień', opis: 'ciągłość treningowa' },
  { id: 34, typ: 'S', kategoria: 'B', kategoriaNazwa: 'TRENING / CIAŁO', nazwa: 'Weteran FBW', opis: '6 miesięcy regularnego treningu od powrotu po przerwie' },
  { id: 35, typ: 'S', kategoria: 'B', kategoriaNazwa: 'TRENING / CIAŁO', nazwa: 'Rocznik', opis: '1 rok od powrotu na siłownię w systemie' },
  { id: 36, typ: 'Z', kategoria: 'B', kategoriaNazwa: 'TRENING / CIAŁO', nazwa: 'Nowy poziom obciążenia', opis: 'pierwszy raz przekroczony próg [do skalibrowania: np. 100kg suma martwy+przysiad+wyciskanie]' },
  { id: 37, typ: 'S', kategoria: 'B', kategoriaNazwa: 'TRENING / CIAŁO', nazwa: 'Konsekwentna rozgrzewka', opis: '30 sesji z odhaczoną rozgrzewką' },
  { id: 38, typ: 'S', kategoria: 'B', kategoriaNazwa: 'TRENING / CIAŁO', nazwa: 'Techniczna precyzja', opis: '20 sesji bez zgłoszonego pogorszenia techniki w notatkach' },
  { id: 39, typ: 'S', kategoria: 'B', kategoriaNazwa: 'TRENING / CIAŁO', nazwa: 'Sekretna: Rehabilitacja zakończona', opis: 'odblokowana, gdy statystyki treningowe (objętość/ciężar) przekroczą poziom sprzed 2-letniej przerwy (wymaga danych historycznych od Arka, jeśli dostępne)' },
  { id: 40, typ: 'S', kategoria: 'B', kategoriaNazwa: 'TRENING / CIAŁO', nazwa: 'Rytm trzech dni', opis: '50 tygodni z pełnymi 3 sesjami (odpowiednik "prawie roku" konsekwencji)' },
  { id: 41, typ: 'Z', kategoria: 'B', kategoriaNazwa: 'TRENING / CIAŁO', nazwa: 'Dzień mocy', opis: 'sesja z co najmniej 2 progresjami ciężaru naraz' },
  { id: 42, typ: 'S', kategoria: 'B', kategoriaNazwa: 'TRENING / CIAŁO', nazwa: 'Budowniczy od podstaw', opis: 'ukończona pełna 8-tygodniowa faza startowa planu A/B' },
  { id: 43, typ: 'S', kategoria: 'B', kategoriaNazwa: 'TRENING / CIAŁO', nazwa: 'Czwarty dzień', opis: 'pierwsza sesja po ewentualnym dodaniu 4. dnia treningowego (milestone z Modułu 2)' },
  { id: 44, typ: 'S', kategoria: 'B', kategoriaNazwa: 'TRENING / CIAŁO', nazwa: 'Sto serii', opis: '100 zarejestrowanych serii łącznie (dowolne ćwiczenia)' },
  { id: 45, typ: 'S', kategoria: 'B', kategoriaNazwa: 'TRENING / CIAŁO', nazwa: 'Tysiąc serii', opis: '1000 serii łącznie' },
  { id: 46, typ: 'S', kategoria: 'C', kategoriaNazwa: 'KARDIO + MOBILNOŚĆ', nazwa: 'Pierwszy krok mobilności', opis: 'pierwsza sesja kardio z kettlami po treningu' },
  { id: 47, typ: 'Z', kategoria: 'C', kategoriaNazwa: 'KARDIO + MOBILNOŚĆ', nazwa: 'Tydzień mobilności', opis: 'kardio/mobilność po każdym z 3 treningów w tygodniu' },
  { id: 48, typ: 'S', kategoria: 'C', kategoriaNazwa: 'KARDIO + MOBILNOŚĆ', nazwa: 'Miesiąc mobilności', opis: '12 sesji w 30 dni' },
  { id: 49, typ: 'S', kategoria: 'C', kategoriaNazwa: 'KARDIO + MOBILNOŚĆ', nazwa: 'Otwarte biodra', opis: '20 sesji ukierunkowanych na mobilność bioder (po dostarczeniu bazy CrossFit)' },
  { id: 50, typ: 'S', kategoria: 'C', kategoriaNazwa: 'KARDIO + MOBILNOŚĆ', nazwa: 'Ruchome barki', opis: '20 sesji ukierunkowanych na mobilność barków' },
  { id: 51, typ: 'S', kategoria: 'C', kategoriaNazwa: 'KARDIO + MOBILNOŚĆ', nazwa: 'Fundament pod matę', opis: '50 sesji mobilności łącznie, przed startem BJJ' },
  { id: 52, typ: 'S', kategoria: 'C', kategoriaNazwa: 'KARDIO + MOBILNOŚĆ', nazwa: 'Wydolność w budowie', opis: '3 miesiące regularnego kardio potreningowego' },
  { id: 53, typ: 'Z', kategoria: 'C', kategoriaNazwa: 'KARDIO + MOBILNOŚĆ', nazwa: 'Intensywny tydzień', opis: 'wszystkie sesje tygodnia z notatką "wysoka intensywność"' },
  { id: 54, typ: 'S', kategoria: 'C', kategoriaNazwa: 'KARDIO + MOBILNOŚĆ', nazwa: 'Sto sesji kardio', opis: '100 sesji łącznie' },
  { id: 55, typ: 'S', kategoria: 'C', kategoriaNazwa: 'KARDIO + MOBILNOŚĆ', nazwa: 'Baza CrossFit wdrożona', opis: 'pierwsza sesja wykorzystująca bibliotekę ćwiczeń od trenera' },
  { id: 56, typ: 'S', kategoria: 'C', kategoriaNazwa: 'KARDIO + MOBILNOŚĆ', nazwa: 'Sekretna: Gotowość do maty', opis: 'odblokowana automatycznie w miesiącu poprzedzającym deklarowany start BJJ (na podstawie Modułu 13)' },
  { id: 57, typ: 'S', kategoria: 'C', kategoriaNazwa: 'KARDIO + MOBILNOŚĆ', nazwa: 'Pełny zakres', opis: 'subiektywna notatka "pełny zakres ruchu bez ograniczeń" w 10 sesjach z rzędu' },
  { id: 58, typ: 'S', kategoria: 'D', kategoriaNazwa: 'DIETA', nazwa: 'Pierwszy pełny dzień', opis: '5/5 posiłków w jeden dzień' },
  { id: 59, typ: 'Z', kategoria: 'D', kategoriaNazwa: 'DIETA', nazwa: 'Tydzień pełnych posiłków', opis: '7 dni z rzędu 5/5' },
  { id: 60, typ: 'S', kategoria: 'D', kategoriaNazwa: 'DIETA', nazwa: 'Miesiąc regularności żywieniowej', opis: '25+/30 dni z pełnymi posiłkami' },
  { id: 61, typ: 'S', kategoria: 'D', kategoriaNazwa: 'DIETA', nazwa: 'Kwartał nawyku', opis: '3 miesiące konsekwentnego wzorca posiłków' },
  { id: 62, typ: 'S', kategoria: 'D', kategoriaNazwa: 'DIETA', nazwa: 'Białkowy start', opis: '30 dni z rzędu z odhaczonym naciskiem na białko w Posiłku 1' },
  { id: 63, typ: 'S', kategoria: 'D', kategoriaNazwa: 'DIETA', nazwa: 'Bez przetworzonego', opis: '30 dni bez zgłoszonego cheat mealu' },
  { id: 64, typ: 'Z', kategoria: 'D', kategoriaNazwa: 'DIETA', nazwa: 'Czysty tydzień', opis: '7 dni bez cheat mealu/cheat daya' },
  { id: 65, typ: 'S', kategoria: 'D', kategoriaNazwa: 'DIETA', nazwa: 'Sucha masa w budowie', opis: '3 miesiące diety z celem masy bez odnotowanego znacznego przyrostu tkanki tłuszczowej (subiektywna ocena Arka)' },
  { id: 66, typ: 'S', kategoria: 'D', kategoriaNazwa: 'DIETA', nazwa: 'Setka posiłków', opis: '100 odhaczonych posiłków łącznie' },
  { id: 67, typ: 'S', kategoria: 'D', kategoriaNazwa: 'DIETA', nazwa: 'Pięćset posiłków', opis: '500 posiłków łącznie' },
  { id: 68, typ: 'S', kategoria: 'D', kategoriaNazwa: 'DIETA', nazwa: 'Tysiąc posiłków', opis: '1000 posiłków łącznie' },
  { id: 69, typ: 'S', kategoria: 'D', kategoriaNazwa: 'DIETA', nazwa: 'Gainer konsekwentny', opis: '50 sesji treningowych z odhaczonym gainerem' },
  { id: 70, typ: 'Z', kategoria: 'D', kategoriaNazwa: 'DIETA', nazwa: 'Idealny tydzień żywieniowy', opis: '5/5 posiłków każdego dnia przez 7 dni + zero cheat meali' },
  { id: 71, typ: 'S', kategoria: 'D', kategoriaNazwa: 'DIETA', nazwa: 'Sekretna: Nawyk ponad restrykcję', opis: 'odblokowana po 6 miesiącach bez ani jednego dnia z zerem posiłków (odzwierciedla filozofię "nawyki, nie restrykcje")' },
  { id: 72, typ: 'S', kategoria: 'D', kategoriaNazwa: 'DIETA', nazwa: 'Rok przy stole', opis: '1 rok konsekwentnego trackingu posiłków' },
  { id: 73, typ: 'S', kategoria: 'E', kategoriaNazwa: 'CZYTELNICTWO / UMYSŁ', nazwa: 'Pierwsza godzina', opis: 'pierwszy dzień z 60 min czytania/słuchania' },
  { id: 74, typ: 'Z', kategoria: 'E', kategoriaNazwa: 'CZYTELNICTWO / UMYSŁ', nazwa: 'Tydzień czytelnika', opis: 'średnia 7-dniowa ≥55 min' },
  { id: 75, typ: 'S', kategoria: 'E', kategoriaNazwa: 'CZYTELNICTWO / UMYSŁ', nazwa: 'Miesiąc w książkach', opis: 'średnia 30-dniowa ≥55 min' },
  { id: 76, typ: 'S', kategoria: 'E', kategoriaNazwa: 'CZYTELNICTWO / UMYSŁ', nazwa: 'Pierwsza ukończona książka/audiobook w systemie', opis: '' },
  { id: 77, typ: 'S', kategoria: 'E', kategoriaNazwa: 'CZYTELNICTWO / UMYSŁ', nazwa: 'Piątka', opis: '5 ukończonych pozycji' },
  { id: 78, typ: 'S', kategoria: 'E', kategoriaNazwa: 'CZYTELNICTWO / UMYSŁ', nazwa: 'Dziesiątka', opis: '10 ukończonych pozycji' },
  { id: 79, typ: 'S', kategoria: 'E', kategoriaNazwa: 'CZYTELNICTWO / UMYSŁ', nazwa: 'Dwudziestka pięć', opis: '25 ukończonych pozycji' },
  { id: 80, typ: 'S', kategoria: 'E', kategoriaNazwa: 'CZYTELNICTWO / UMYSŁ', nazwa: 'Pięćdziesiątka', opis: '50 ukończonych pozycji' },
  { id: 81, typ: 'S', kategoria: 'E', kategoriaNazwa: 'CZYTELNICTWO / UMYSŁ', nazwa: 'Setka godzin', opis: '100h łącznego czasu czytania/słuchania' },
  { id: 82, typ: 'S', kategoria: 'E', kategoriaNazwa: 'CZYTELNICTWO / UMYSŁ', nazwa: 'Pięćset godzin', opis: '500h łącznie' },
  { id: 83, typ: 'S', kategoria: 'E', kategoriaNazwa: 'CZYTELNICTWO / UMYSŁ', nazwa: 'Tysiąc godzin', opis: '1000h łącznie' },
  { id: 84, typ: 'S', kategoria: 'E', kategoriaNazwa: 'CZYTELNICTWO / UMYSŁ', nazwa: 'Komiksowy koneser', opis: '10 przeczytanych komiksów odnotowanych w systemie' },
  { id: 85, typ: 'Z', kategoria: 'E', kategoriaNazwa: 'CZYTELNICTWO / UMYSŁ', nazwa: 'Maraton wiedzy', opis: '3h czytania/słuchania w jeden dzień' },
  { id: 86, typ: 'S', kategoria: 'E', kategoriaNazwa: 'CZYTELNICTWO / UMYSŁ', nazwa: 'Audiobook w drodze', opis: '20 sesji słuchania podczas dojazdu do pracy' },
  { id: 87, typ: 'S', kategoria: 'E', kategoriaNazwa: 'CZYTELNICTWO / UMYSŁ', nazwa: 'Dogrywka mistrzowska', opis: '10 przypadków skorzystania z mechanizmu "wydłużony czas przed snem na czytanie" (Moduł 19) bez zaniedbania higieny światła' },
  { id: 88, typ: 'S', kategoria: 'E', kategoriaNazwa: 'CZYTELNICTWO / UMYSŁ', nazwa: 'Rok czytelnika', opis: '1 rok konsekwentnego trackingu czytelnictwa' },
  { id: 89, typ: 'S', kategoria: 'E', kategoriaNazwa: 'CZYTELNICTWO / UMYSŁ', nazwa: 'Sekretna: Erudyta', opis: 'odblokowana po ukończeniu pozycji z 5 różnych gatunków/kategorii' },
  { id: 90, typ: 'S', kategoria: 'E', kategoriaNazwa: 'CZYTELNICTWO / UMYSŁ', nazwa: 'Zrównoważony umysł', opis: '90 dni ze średnią rolling-average w normie (patrz Moduł 20) bez ani jednego dnia zerowego' },
  { id: 91, typ: 'S', kategoria: 'F', kategoriaNazwa: 'PIELĘGNACJA', nazwa: 'Pierwszy rytuał', opis: 'pierwszy w pełni odhaczony dzień pielęgnacyjny (wszystkie zaplanowane pozycje)' },
  { id: 92, typ: 'Z', kategoria: 'F', kategoriaNazwa: 'PIELĘGNACJA', nazwa: 'Tydzień w formie', opis: '7 dni z rzędu pełnej pielęgnacji' },
  { id: 93, typ: 'S', kategoria: 'F', kategoriaNazwa: 'PIELĘGNACJA', nazwa: 'Miesiąc dbałości', opis: '25+/30 dni' },
  { id: 94, typ: 'S', kategoria: 'F', kategoriaNazwa: 'PIELĘGNACJA', nazwa: 'Fryzjer w rytmie', opis: '10 wizyt u fryzjera zgodnie z cyklem 3-tygodniowym' },
  { id: 95, typ: 'S', kategoria: 'F', kategoriaNazwa: 'PIELĘGNACJA', nazwa: 'Nizoral konsekwentny', opis: '20 tygodni z dotrzymanym rytmem niedziela+środa' },
  { id: 96, typ: 'S', kategoria: 'F', kategoriaNazwa: 'PIELĘGNACJA', nazwa: 'Skóra w formie', opis: '90 dni z rzędu odhaczonego kremu do twarzy (oba sloty)' },
  { id: 97, typ: 'S', kategoria: 'F', kategoriaNazwa: 'PIELĘGNACJA', nazwa: 'Ręce jak nowe', opis: '90 dni z rzędu kremu do rąk (oba sloty)' },
  { id: 98, typ: 'S', kategoria: 'F', kategoriaNazwa: 'PIELĘGNACJA', nazwa: 'Rok pielęgnacji', opis: '1 rok konsekwentnego trackingu' },
  { id: 99, typ: 'S', kategoria: 'F', kategoriaNazwa: 'PIELĘGNACJA', nazwa: 'Setka rytuałów', opis: '100 w pełni odhaczonych dni pielęgnacyjnych' },
  { id: 100, typ: 'S', kategoria: 'F', kategoriaNazwa: 'PIELĘGNACJA', nazwa: 'Sekretna: Detal ma znaczenie', opis: 'odblokowana po 6 miesiącach bez ani jednego całkowicie pominiętego dnia pielęgnacji' },
  { id: 101, typ: 'S', kategoria: 'G', kategoriaNazwa: 'SPACER Z PSEM', nazwa: 'Pierwszy spacer w systemie', opis: '' },
  { id: 102, typ: 'Z', kategoria: 'G', kategoriaNazwa: 'SPACER Z PSEM', nazwa: 'Tydzień ruchu z psem', opis: 'min. 2 spacery dziennie przez 7 dni' },
  { id: 103, typ: 'S', kategoria: 'G', kategoriaNazwa: 'SPACER Z PSEM', nazwa: 'Setka spacerów', opis: '100 spacerów łącznie' },
  { id: 104, typ: 'S', kategoria: 'G', kategoriaNazwa: 'SPACER Z PSEM', nazwa: 'Pięćset spacerów', opis: '500 spacerów łącznie' },
  { id: 105, typ: 'S', kategoria: 'G', kategoriaNazwa: 'SPACER Z PSEM', nazwa: 'Tysiąc spacerów', opis: '1000 spacerów łącznie' },
  { id: 106, typ: 'S', kategoria: 'G', kategoriaNazwa: 'SPACER Z PSEM', nazwa: 'Bez przypomnień', opis: '6 miesięcy konsekwentnych spacerów mimo braku remindera (odzwierciedla świadomą decyzję Arka o rezygnacji z powiadomień w tym module)' },
  { id: 107, typ: 'S', kategoria: 'G', kategoriaNazwa: 'SPACER Z PSEM', nazwa: 'Towarzysz w każdą pogodę', opis: '12 miesięcy trackingu niezależnie od sezonu' },
  { id: 108, typ: 'S', kategoria: 'G', kategoriaNazwa: 'SPACER Z PSEM', nazwa: 'Sekretna: Więź', opis: 'odblokowana po roku konsekwentnych spacerów (odzwierciedla relację z psem, nie tylko metrykę)' },
  { id: 109, typ: 'S', kategoria: 'H', kategoriaNazwa: 'SPRZĄTANIE / OTOCZENIE', nazwa: 'Pierwsza strefa', opis: 'pierwsze ukończone zadanie rotacji 7-strefowej' },
  { id: 110, typ: 'Z', kategoria: 'H', kategoriaNazwa: 'SPRZĄTANIE / OTOCZENIE', nazwa: 'Pełny tydzień rotacji', opis: 'wszystkie 7 stref odhaczone w tygodniu' },
  { id: 111, typ: 'S', kategoria: 'H', kategoriaNazwa: 'SPRZĄTANIE / OTOCZENIE', nazwa: 'Miesiąc porządku', opis: '4 pełne tygodnie rotacji z rzędu' },
  { id: 112, typ: 'S', kategoria: 'H', kategoriaNazwa: 'SPRZĄTANIE / OTOCZENIE', nazwa: 'Kwartał w ryzach', opis: '3 miesiące konsekwentnej rotacji' },
  { id: 113, typ: 'S', kategoria: 'H', kategoriaNazwa: 'SPRZĄTANIE / OTOCZENIE', nazwa: 'Setka zadań', opis: '100 ukończonych zadań sprzątania łącznie' },
  { id: 114, typ: 'S', kategoria: 'H', kategoriaNazwa: 'SPRZĄTANIE / OTOCZENIE', nazwa: 'Mistrz łazienki', opis: '20 ukończonych zadań strefy Łazienka' },
  { id: 115, typ: 'S', kategoria: 'H', kategoriaNazwa: 'SPRZĄTANIE / OTOCZENIE', nazwa: 'Mistrz kuchni', opis: '20 ukończonych zadań strefy Kuchnia' },
  { id: 116, typ: 'S', kategoria: 'H', kategoriaNazwa: 'SPRZĄTANIE / OTOCZENIE', nazwa: 'Porządek globalny', opis: '20 niedzielnych sprzątań globalnych' },
  { id: 117, typ: 'S', kategoria: 'H', kategoriaNazwa: 'SPRZĄTANIE / OTOCZENIE', nazwa: 'Floor zawsze spełniony', opis: '60 dni z rzędu z dotrzymanym minimum 15 min w tagu #sprzątanie' },
  { id: 118, typ: 'S', kategoria: 'H', kategoriaNazwa: 'SPRZĄTANIE / OTOCZENIE', nazwa: 'W granicach ceiling', opis: '60 dni bez przekroczenia 60 min w tagu #sprzątanie (dyscyplina, nie tylko wykonanie)' },
  { id: 119, typ: 'Z', kategoria: 'H', kategoriaNazwa: 'SPRZĄTANIE / OTOCZENIE', nazwa: 'Dzień generalny', opis: 'dzień z odhaczonymi wszystkimi możliwymi zadaniami sprzątania (mieszkanie + auto)' },
  { id: 120, typ: 'S', kategoria: 'H', kategoriaNazwa: 'SPRZĄTANIE / OTOCZENIE', nazwa: 'Rok w porządku', opis: '1 rok konsekwentnej rotacji' },
  { id: 121, typ: 'S', kategoria: 'H', kategoriaNazwa: 'SPRZĄTANIE / OTOCZENIE', nazwa: 'Sekretna: Symbioza z robotem', opis: 'odblokowana po 6 miesiącach bez przerwy w harmonogramie robota sprzątającego' },
  { id: 122, typ: 'S', kategoria: 'H', kategoriaNazwa: 'SPRZĄTANIE / OTOCZENIE', nazwa: 'Przedsionek i klatka', opis: '20 ukończonych zadań tej konkretnej strefy (najrzadziej wybierana intuicyjnie, więc osobne wyróżnienie)' },
  { id: 123, typ: 'S', kategoria: 'I', kategoriaNazwa: 'SEN / HIGIENA ŚWIATŁA', nazwa: 'Pierwsza ciemna noc', opis: 'pierwszy odhaczony checkbox redukcji światła wieczorem' },
  { id: 124, typ: 'Z', kategoria: 'I', kategoriaNazwa: 'SEN / HIGIENA ŚWIATŁA', nazwa: 'Tydzień higieny snu', opis: '7 dni z rzędu odhaczonej redukcji światła' },
  { id: 125, typ: 'S', kategoria: 'I', kategoriaNazwa: 'SEN / HIGIENA ŚWIATŁA', nazwa: 'Miesiąc dyscypliny świetlnej', opis: '25+/30 dni' },
  { id: 126, typ: 'S', kategoria: 'I', kategoriaNazwa: 'SEN / HIGIENA ŚWIATŁA', nazwa: 'Setka ciemnych wieczorów', opis: '100 dni łącznie' },
  { id: 127, typ: 'S', kategoria: 'I', kategoriaNazwa: 'SEN / HIGIENA ŚWIATŁA', nazwa: 'Rytm zmianowy opanowany', opis: '3 miesiące konsekwentnego stosowania się do właściwej pobudki wg typu dnia (A/B/C)' },
  { id: 128, typ: 'S', kategoria: 'I', kategoriaNazwa: 'SEN / HIGIENA ŚWIATŁA', nazwa: 'Bez ekranu przed snem', opis: '60 dni z rzędu' },
  { id: 129, typ: 'S', kategoria: 'I', kategoriaNazwa: 'SEN / HIGIENA ŚWIATŁA', nazwa: 'Rok higieny snu', opis: '1 rok trackingu' },
  { id: 130, typ: 'S', kategoria: 'I', kategoriaNazwa: 'SEN / HIGIENA ŚWIATŁA', nazwa: 'Sekretna: Regeneracja', opis: 'odblokowana, gdy rolling-average jakości snu (Moduł 11) przekroczy 7/10 przez 30 dni z rzędu' },
  { id: 131, typ: 'S', kategoria: 'J', kategoriaNazwa: 'MOOD TRACKER / SAMOPOCZUCIE', nazwa: 'Pierwszy wpis', opis: 'pierwszy w pełni wypełniony mood check (rano+wieczór)' },
  { id: 132, typ: 'Z', kategoria: 'J', kategoriaNazwa: 'MOOD TRACKER / SAMOPOCZUCIE', nazwa: 'Tydzień świadomości', opis: '14/14 wpisów w tygodniu (rano+wieczór × 7 dni)' },
  { id: 133, typ: 'S', kategoria: 'J', kategoriaNazwa: 'MOOD TRACKER / SAMOPOCZUCIE', nazwa: 'Miesiąc obserwacji', opis: '50+/60 wpisów w miesiącu' },
  { id: 134, typ: 'S', kategoria: 'J', kategoriaNazwa: 'MOOD TRACKER / SAMOPOCZUCIE', nazwa: 'Setka wpisów', opis: '100 wpisów łącznie' },
  { id: 135, typ: 'S', kategoria: 'J', kategoriaNazwa: 'MOOD TRACKER / SAMOPOCZUCIE', nazwa: 'Pięćset wpisów', opis: '500 wpisów łącznie' },
  { id: 136, typ: 'S', kategoria: 'J', kategoriaNazwa: 'MOOD TRACKER / SAMOPOCZUCIE', nazwa: 'Tysiąc wpisów', opis: '1000 wpisów łącznie' },
  { id: 137, typ: 'S', kategoria: 'J', kategoriaNazwa: 'MOOD TRACKER / SAMOPOCZUCIE', nazwa: 'Rok samoobserwacji', opis: '1 rok konsekwentnego trackingu' },
  { id: 138, typ: 'S', kategoria: 'J', kategoriaNazwa: 'MOOD TRACKER / SAMOPOCZUCIE', nazwa: 'Detektyw GI', opis: '10 przypadków wypełnionej retrospekcji żywieniowej po niskim wyniku GI (nagroda za współpracę z systemem, nie za same objawy)' },
  { id: 139, typ: 'S', kategoria: 'J', kategoriaNazwa: 'MOOD TRACKER / SAMOPOCZUCIE', nazwa: 'Stabilny trend', opis: '30 dni z rzędu bez wyniku poniżej 4/10 w żadnej kategorii' },
  { id: 140, typ: 'S', kategoria: 'J', kategoriaNazwa: 'MOOD TRACKER / SAMOPOCZUCIE', nazwa: 'Sekretna: Gotowość na AI Coacha', opis: 'odblokowana automatycznie po zebraniu wystarczających danych do aktywacji Modułu 14 (4-6 tygodni)' },
  { id: 141, typ: 'S', kategoria: 'K', kategoriaNazwa: 'PORTFOLIO FIGUREK / PERSONAL BRAND', nazwa: 'Pierwszy projekt', opis: 'pierwszy zarejestrowany projekt w systemie' },
  { id: 142, typ: 'S', kategoria: 'K', kategoriaNazwa: 'PORTFOLIO FIGUREK / PERSONAL BRAND', nazwa: 'Pierwsza ukończona figurka', opis: '' },
  { id: 143, typ: 'S', kategoria: 'K', kategoriaNazwa: 'PORTFOLIO FIGUREK / PERSONAL BRAND', nazwa: 'Piątka portfolio', opis: '5 ukończonych projektów' },
  { id: 144, typ: 'S', kategoria: 'K', kategoriaNazwa: 'PORTFOLIO FIGUREK / PERSONAL BRAND', nazwa: 'Dziesiątka portfolio', opis: '10 ukończonych projektów' },
  { id: 145, typ: 'S', kategoria: 'K', kategoriaNazwa: 'PORTFOLIO FIGUREK / PERSONAL BRAND', nazwa: 'Dwudziestka pięć', opis: '25 ukończonych projektów' },
  { id: 146, typ: 'S', kategoria: 'K', kategoriaNazwa: 'PORTFOLIO FIGUREK / PERSONAL BRAND', nazwa: 'Pięćdziesiątka', opis: '50 ukończonych projektów' },
  { id: 147, typ: 'S', kategoria: 'K', kategoriaNazwa: 'PORTFOLIO FIGUREK / PERSONAL BRAND', nazwa: 'Setka', opis: '100 ukończonych projektów' },
  { id: 148, typ: 'S', kategoria: 'K', kategoriaNazwa: 'PORTFOLIO FIGUREK / PERSONAL BRAND', nazwa: 'Pierwsza publikacja', opis: 'pierwszy projekt z pełnym checklistem publikacji (zdjęcie+opis+opublikowane)' },
  { id: 149, typ: 'S', kategoria: 'K', kategoriaNazwa: 'PORTFOLIO FIGUREK / PERSONAL BRAND', nazwa: 'Dziesięć publikacji', opis: '' },
  { id: 150, typ: 'S', kategoria: 'K', kategoriaNazwa: 'PORTFOLIO FIGUREK / PERSONAL BRAND', nazwa: 'Pięćdziesiąt publikacji', opis: '' },
  { id: 151, typ: 'S', kategoria: 'K', kategoriaNazwa: 'PORTFOLIO FIGUREK / PERSONAL BRAND', nazwa: 'Konsystentny twórca', opis: '8 tygodni z rzędu z minimum 1 publikacją tygodniowo (zgodnie ze strategią z Modułu 18: regularność > ilość)' },
  { id: 152, typ: 'S', kategoria: 'K', kategoriaNazwa: 'PORTFOLIO FIGUREK / PERSONAL BRAND', nazwa: 'Kwartał marki', opis: '3 miesiące konsekwentnej obecności publikacyjnej' },
  { id: 153, typ: 'S', kategoria: 'K', kategoriaNazwa: 'PORTFOLIO FIGUREK / PERSONAL BRAND', nazwa: 'Pół roku budowania marki', opis: '6 miesięcy' },
  { id: 154, typ: 'S', kategoria: 'K', kategoriaNazwa: 'PORTFOLIO FIGUREK / PERSONAL BRAND', nazwa: 'Rok Personal Brand', opis: '1 rok konsekwentnego rozwoju portfolio' },
  { id: 155, typ: 'S', kategoria: 'K', kategoriaNazwa: 'PORTFOLIO FIGUREK / PERSONAL BRAND', nazwa: 'Kalibracja mistrzowska', opis: '10 projektów z różnicą szacowany/rzeczywisty czas poniżej 15% (system nauczył się Twojego tempa)' },
  { id: 156, typ: 'S', kategoria: 'K', kategoriaNazwa: 'PORTFOLIO FIGUREK / PERSONAL BRAND', nazwa: 'Mała ale wytrwała', opis: '10 ukończonych "Małych figurek"' },
  { id: 157, typ: 'S', kategoria: 'K', kategoriaNazwa: 'PORTFOLIO FIGUREK / PERSONAL BRAND', nazwa: 'Średniozaawansowany warsztat', opis: '10 ukończonych "Średnich figurek"' },
  { id: 158, typ: 'S', kategoria: 'K', kategoriaNazwa: 'PORTFOLIO FIGUREK / PERSONAL BRAND', nazwa: 'Duże wyzwanie', opis: '5 ukończonych "Dużych/złożonych figurek"' },
  { id: 159, typ: 'S', kategoria: 'K', kategoriaNazwa: 'PORTFOLIO FIGUREK / PERSONAL BRAND', nazwa: 'Cały oddział', opis: 'pierwszy ukończony "Cały zestaw/oddział"' },
  { id: 160, typ: 'Z', kategoria: 'K', kategoriaNazwa: 'PORTFOLIO FIGUREK / PERSONAL BRAND', nazwa: 'Tydzień praktyki', opis: 'min. 3 sesje praktyki (malowanie lub kolorowanki) w tygodniu' },
  { id: 161, typ: 'S', kategoria: 'K', kategoriaNazwa: 'PORTFOLIO FIGUREK / PERSONAL BRAND', nazwa: 'Trening oka i ręki', opis: '50 sesji z kolorowankami jako praktyka' },
  { id: 162, typ: 'S', kategoria: 'K', kategoriaNazwa: 'PORTFOLIO FIGUREK / PERSONAL BRAND', nazwa: 'Sekretna: Niezależność', opis: 'odblokowana przy pierwszym projekcie oznaczonym jako zlecenie niezależne (poza Neon Forge Studio) — milestone realnego celu zawodowego Arka' },
  { id: 163, typ: 'S', kategoria: 'L', kategoriaNazwa: 'AUTO + MOTOCYKL', nazwa: 'Pierwszy przegląd auta w systemie', opis: '' },
  { id: 164, typ: 'S', kategoria: 'L', kategoriaNazwa: 'AUTO + MOTOCYKL', nazwa: 'Rok w trasie', opis: '12 miesięcy konsekwentnych comiesięcznych przeglądów auta' },
  { id: 165, typ: 'S', kategoria: 'L', kategoriaNazwa: 'AUTO + MOTOCYKL', nazwa: 'Pierwsza wiosna', opis: 'pierwsze wiosenne przygotowanie motocykla w systemie' },
  { id: 166, typ: 'S', kategoria: 'L', kategoriaNazwa: 'AUTO + MOTOCYKL', nazwa: 'Pierwsza zima', opis: 'pierwsze jesienne odłożenie motocykla na zimę' },
  { id: 167, typ: 'S', kategoria: 'L', kategoriaNazwa: 'AUTO + MOTOCYKL', nazwa: 'Pełny sezon', opis: 'kwiecień-październik z dotrzymanymi wszystkimi comiesięcznymi kontrolami motocykla' },
  { id: 168, typ: 'S', kategoria: 'L', kategoriaNazwa: 'AUTO + MOTOCYKL', nazwa: 'Trzy sezony', opis: '3 pełne sezony motocyklowe z konsekwentną opieką' },
  { id: 169, typ: 'S', kategoria: 'L', kategoriaNazwa: 'AUTO + MOTOCYKL', nazwa: 'Mechanik-amator', opis: '20 łącznie odhaczonych zadań konserwacyjnych (auto+motocykl razem)' },
  { id: 170, typ: 'Z', kategoria: 'L', kategoriaNazwa: 'AUTO + MOTOCYKL', nazwa: 'Miesiąc na kołach', opis: 'wszystkie zaplanowane zadania pojazdów w danym miesiącu odhaczone' },
  { id: 171, typ: 'S', kategoria: 'L', kategoriaNazwa: 'AUTO + MOTOCYKL', nazwa: 'Pięć lat w garażu', opis: '5 sezonów motocyklowych (cel bardzo długoterminowy)' },
  { id: 172, typ: 'S', kategoria: 'L', kategoriaNazwa: 'AUTO + MOTOCYKL', nazwa: 'Sekretna: Dwa kółka, cztery kółka', opis: 'odblokowana po pierwszym miesiącu z pełną opieką nad OBOMA pojazdami naraz' },
  { id: 173, typ: 'S', kategoria: 'M', kategoriaNazwa: 'ZAKUPY', nazwa: 'Pierwsza lista 70/30', opis: 'pierwsze zrealizowane zakupy wg rekomendacji systemu' },
  { id: 174, typ: 'Z', kategoria: 'M', kategoriaNazwa: 'ZAKUPY', nazwa: 'Miesiąc świadomych zakupów', opis: '4 tygodnie z rzędu z odhaczoną listą' },
  { id: 175, typ: 'S', kategoria: 'M', kategoriaNazwa: 'ZAKUPY', nazwa: 'Setka list', opis: '100 zrealizowanych cotygodniowych list zakupowych' },
  { id: 176, typ: 'S', kategoria: 'M', kategoriaNazwa: 'ZAKUPY', nazwa: 'Łowca promocji', opis: '20 przypadków odnotowanego skorzystania z promocji Aldi po sprawdzeniu gazetki' },
  { id: 177, typ: 'S', kategoria: 'M', kategoriaNazwa: 'ZAKUPY', nazwa: 'Rotacja bez rutyny', opis: '20 tygodni z odhaczoną co najmniej 1 pozycją z "30% rotacyjnych" w każdej kategorii' },
  { id: 178, typ: 'S', kategoria: 'M', kategoriaNazwa: 'ZAKUPY', nazwa: 'Rok przy wózku', opis: '1 rok konsekwentnego trackingu zakupów' },
  { id: 179, typ: 'Z', kategoria: 'N', kategoriaNazwa: 'STREAKI OGÓLNE / PERFECT DAY', nazwa: 'Pierwszy Perfect Day', opis: 'pierwszy dzień ze 100% ukończeniem wszystkich zaplanowanych zadań' },
  { id: 180, typ: 'Z', kategoria: 'N', kategoriaNazwa: 'STREAKI OGÓLNE / PERFECT DAY', nazwa: 'Tydzień doskonałości', opis: '7 Perfect Days w jednym tygodniu (rzadkie, bardzo wymagające)' },
  { id: 181, typ: 'S', kategoria: 'N', kategoriaNazwa: 'STREAKI OGÓLNE / PERFECT DAY', nazwa: 'Dziesięć Perfect Days łącznie (niekoniecznie z rzędu)', opis: '' },
  { id: 182, typ: 'S', kategoria: 'N', kategoriaNazwa: 'STREAKI OGÓLNE / PERFECT DAY', nazwa: 'Pięćdziesiąt Perfect Days łącznie', opis: '' },
  { id: 183, typ: 'S', kategoria: 'N', kategoriaNazwa: 'STREAKI OGÓLNE / PERFECT DAY', nazwa: 'Setka Perfect Days łącznie', opis: '' },
  { id: 184, typ: 'Z', kategoria: 'N', kategoriaNazwa: 'STREAKI OGÓLNE / PERFECT DAY', nazwa: 'Streak 7', opis: '7 dni z rzędu ≥80% ukończenia dnia' },
  { id: 185, typ: 'Z', kategoria: 'N', kategoriaNazwa: 'STREAKI OGÓLNE / PERFECT DAY', nazwa: 'Streak 14', opis: '14 dni z rzędu ≥80%' },
  { id: 186, typ: 'S', kategoria: 'N', kategoriaNazwa: 'STREAKI OGÓLNE / PERFECT DAY', nazwa: 'Streak 30', opis: '30 dni z rzędu ≥80% (przekracza próg "sezonowy", staje się trwałym osiągnięciem przy pierwszym osiągnięciu)' },
  { id: 187, typ: 'S', kategoria: 'N', kategoriaNazwa: 'STREAKI OGÓLNE / PERFECT DAY', nazwa: 'Streak 60', opis: '60 dni z rzędu' },
  { id: 188, typ: 'S', kategoria: 'N', kategoriaNazwa: 'STREAKI OGÓLNE / PERFECT DAY', nazwa: 'Streak 90', opis: '90 dni z rzędu' },
  { id: 189, typ: 'S', kategoria: 'N', kategoriaNazwa: 'STREAKI OGÓLNE / PERFECT DAY', nazwa: 'Streak 180', opis: 'pół roku bez przerwy ≥80%' },
  { id: 190, typ: 'S', kategoria: 'N', kategoriaNazwa: 'STREAKI OGÓLNE / PERFECT DAY', nazwa: 'Streak 365', opis: 'cały rok' },
  { id: 191, typ: 'S', kategoria: 'N', kategoriaNazwa: 'STREAKI OGÓLNE / PERFECT DAY', nazwa: 'Feniks', opis: 'pierwszy powrót do streaka po jego zerwaniu (odzwierciedla resilience, nie tylko konsekwencję)' },
  { id: 192, typ: 'S', kategoria: 'N', kategoriaNazwa: 'STREAKI OGÓLNE / PERFECT DAY', nazwa: 'Wszystkie 5 atrybutów', opis: 'dzień z 100% ukończeniem we WSZYSTKICH 5 Atrybutach naraz' },
  { id: 193, typ: 'S', kategoria: 'N', kategoriaNazwa: 'STREAKI OGÓLNE / PERFECT DAY', nazwa: 'Sekretna: Rok z systemem', opis: 'odblokowana po 365 dniach od pierwszego uruchomienia systemu, niezależnie od jakości wykonania (nagroda za sam fakt wytrwania)' },
  { id: 194, typ: 'S', kategoria: 'O', kategoriaNazwa: 'MILESTONE\'Y DŁUGOTERMINOWE / SEKRETNE', nazwa: 'Sekretna: Pierwszy miesiąc', opis: 'przetrwanie pierwszych 30 dni z systemem (próg, na którym najwięcej ludzi porzuca nowe nawyki — świadomie nagrodzony)' },
  { id: 195, typ: 'S', kategoria: 'O', kategoriaNazwa: 'MILESTONE\'Y DŁUGOTERMINOWE / SEKRETNE', nazwa: 'Sekretna: Dolina cienia', opis: 'odblokowana po pierwszej "śmierci postaci" i kontynuacji następnego dnia bez przerwy w używaniu systemu (nagroda za nie-porzucanie po porażce, zgodnie z filozofią "historia nie jest karząca")' },
  { id: 196, typ: 'S', kategoria: 'O', kategoriaNazwa: 'MILESTONE\'Y DŁUGOTERMINOWE / SEKRETNE', nazwa: 'Sekretna: Trzy doliny', opis: 'przetrwanie i kontynuacja po 3 "śmierciach postaci" łącznie — odzwierciedla, że system wybacza i motywuje dalej mimo trudnej mechaniki HP' },
  { id: 197, typ: 'S', kategoria: 'O', kategoriaNazwa: 'MILESTONE\'Y DŁUGOTERMINOWE / SEKRETNE', nazwa: 'Sekretna: Wiosna wojownika', opis: 'odblokowana automatycznie w pierwszym tygodniu sezonu motocyklowego (kwiecień)' },
  { id: 198, typ: 'S', kategoria: 'O', kategoriaNazwa: 'MILESTONE\'Y DŁUGOTERMINOWE / SEKRETNE', nazwa: 'Sekretna: Gotowość do BJJ', opis: 'odblokowana ręcznie przez Arka, gdy faktycznie zapisze się na zajęcia (Moduł 13 aktywowany)' },
  { id: 199, typ: 'S', kategoria: 'O', kategoriaNazwa: 'MILESTONE\'Y DŁUGOTERMINOWE / SEKRETNE', nazwa: 'Sekretna: Pierwszy krok w boksie', opis: 'analogicznie, po BJJ' },
  { id: 200, typ: 'S', kategoria: 'O', kategoriaNazwa: 'MILESTONE\'Y DŁUGOTERMINOWE / SEKRETNE', nazwa: 'Poziom 10 postaci', opis: 'osiągnięcie 10. poziomu ogólnego' },
  { id: 201, typ: 'S', kategoria: 'O', kategoriaNazwa: 'MILESTONE\'Y DŁUGOTERMINOWE / SEKRETNE', nazwa: 'Poziom 20 postaci (maksymalny)', opis: 'pełne wypełnienie krzywej XP' },
  { id: 202, typ: 'S', kategoria: 'O', kategoriaNazwa: 'MILESTONE\'Y DŁUGOTERMINOWE / SEKRETNE', nazwa: 'Mistrz Ciała', opis: 'Atrybut Ciało osiąga poziom 20' },
  { id: 203, typ: 'S', kategoria: 'O', kategoriaNazwa: 'MILESTONE\'Y DŁUGOTERMINOWE / SEKRETNE', nazwa: 'Mistrz Umysłu', opis: 'Atrybut Umysł osiąga poziom 20' },
  { id: 204, typ: 'S', kategoria: 'O', kategoriaNazwa: 'MILESTONE\'Y DŁUGOTERMINOWE / SEKRETNE', nazwa: 'Mistrz Dyscypliny', opis: 'Atrybut Dyscyplina osiąga poziom 20' },
  { id: 205, typ: 'S', kategoria: 'O', kategoriaNazwa: 'MILESTONE\'Y DŁUGOTERMINOWE / SEKRETNE', nazwa: 'Mistrz Otoczenia', opis: 'Atrybut Otoczenie osiąga poziom 20' },
  { id: 206, typ: 'S', kategoria: 'O', kategoriaNazwa: 'MILESTONE\'Y DŁUGOTERMINOWE / SEKRETNE', nazwa: 'Mistrz Marki Osobistej', opis: 'Atrybut Personal Brand osiąga poziom 20' },
  { id: 207, typ: 'S', kategoria: 'O', kategoriaNazwa: 'MILESTONE\'Y DŁUGOTERMINOWE / SEKRETNE', nazwa: 'Pięć Mistrzostw', opis: 'wszystkie 5 Atrybutów na poziomie 20 (odznaka finałowa, najwyższe osiągnięcie w systemie)' },
  { id: 208, typ: 'S', kategoria: 'O', kategoriaNazwa: 'MILESTONE\'Y DŁUGOTERMINOWE / SEKRETNE', nazwa: 'Sekretna: Rocznica', opis: 'odblokowana dokładnie rok od daty pierwszego uruchomienia systemu, z osobistym podsumowaniem roku (dane z całego roku zebrane w jeden widok)' },
];
